inputs:
  message-ok:
    type: string
    required: true

  message-error:
    type: string
    required: true

  warning:
    type: bool
    required: false
    default: true

runs:
  using: composite

  steps:
    - name: Report result

      env:
        message-ok: ${{inputs.message-ok || env.message-ok}}
        message-error: ${{inputs.message-error || env.message-error}}
        warning: ${{inputs.warning && 'warning' || 'error'}}

      shell: bash
      run: |
        if [ -z "$(git status -s)" ]; then
          echo "::notice::${{env.message-ok}}"
        else
          echo Affected files:
          git status --short | sed "s/^ M /::${{env.warning}}::${{env.message-error}}: /"

          echo
          echo Details:
          git diff --color=always --minimal

          #exit 1
        fi
