add_library(xrGame STATIC)

target_sources(xrGame PRIVATE
    ../xrServerEntities/alife_human_brain.cpp
    ../xrServerEntities/alife_monster_brain.cpp
    ../xrServerEntities/alife_space.cpp
    ../xrServerEntities/character_info.cpp
    ../xrServerEntities/gametype_chooser.cpp
    ../xrServerEntities/LevelGameDef.cpp
    ../xrServerEntities/lua_studio.cpp
    ../xrServerEntities/object_factory.cpp
    ../xrServerEntities/object_factory_register.cpp
    ../xrServerEntities/object_factory_script.cpp
    ../xrServerEntities/object_item_script.cpp
    ../xrServerEntities/pch_script.cpp
    ../xrServerEntities/PHNetState.cpp
    ../xrServerEntities/script_callStack.cpp
    ../xrServerEntities/script_debugger.cpp
    ../xrServerEntities/script_debugger_threads.cpp
    ../xrServerEntities/script_engine.cpp
    ../xrServerEntities/script_engine_export.cpp
    ../xrServerEntities/script_engine_script.cpp
    ../xrServerEntities/script_fcolor_script.cpp
    ../xrServerEntities/script_flags_script.cpp
    ../xrServerEntities/script_fmatrix_script.cpp
    ../xrServerEntities/script_fvector_script.cpp
    ../xrServerEntities/script_ini_file.cpp
    ../xrServerEntities/script_ini_file_script.cpp
    ../xrServerEntities/script_lua_helper.cpp
    ../xrServerEntities/script_net_packet_script.cpp
    ../xrServerEntities/script_process.cpp
    ../xrServerEntities/script_reader_script.cpp
    ../xrServerEntities/script_rtoken_list_script.cpp
    ../xrServerEntities/script_sound_type_script.cpp
    ../xrServerEntities/script_stack_tracker.cpp
    ../xrServerEntities/script_storage.cpp
    ../xrServerEntities/script_thread.cpp
    ../xrServerEntities/script_token_list.cpp
    ../xrServerEntities/script_token_list_script.cpp
    ../xrServerEntities/smart_cast.cpp
    ../xrServerEntities/smart_cast_stats.cpp
    ../xrServerEntities/specific_character.cpp
    ../xrServerEntities/xrServer_Factory.cpp
    ../xrServerEntities/xrServer_Objects.cpp
    ../xrServerEntities/xrServer_Objects_Abstract.cpp
    ../xrServerEntities/xrServer_Objects_ALife.cpp
    ../xrServerEntities/xrServer_Objects_ALife_Items.cpp
    ../xrServerEntities/xrServer_Objects_ALife_Items_script.cpp
    ../xrServerEntities/xrServer_Objects_ALife_Items_script2.cpp
    ../xrServerEntities/xrServer_Objects_ALife_Items_script3.cpp
    ../xrServerEntities/xrServer_Objects_ALife_Monsters.cpp
    ../xrServerEntities/xrServer_Objects_ALife_Monsters_script.cpp
    ../xrServerEntities/xrServer_Objects_ALife_Monsters_script2.cpp
    ../xrServerEntities/xrserver_objects_alife_monsters_script3.cpp
    ../xrServerEntities/xrServer_Objects_ALife_Monsters_script4.cpp
    ../xrServerEntities/xrServer_Objects_ALife_script.cpp
    ../xrServerEntities/xrServer_Objects_ALife_script2.cpp
    ../xrServerEntities/xrServer_Objects_ALife_script3.cpp
    ../xrServerEntities/xrServer_Objects_Alife_Smartcovers.cpp
    ../xrServerEntities/xrServer_Objects_Alife_Smartcovers_script.cpp
    ../xrServerEntities/xrServer_Objects_script.cpp
    ../xrServerEntities/xrServer_Objects_script2.cpp
    ../xrServerEntities/xrServer_Object_Base.cpp
    account_manager.cpp
    account_manager_console.cpp
    account_manager_script.cpp
    action_base_script.cpp
    action_planner_action_script.cpp
    action_planner_script.cpp
    ActivatingCharCollisionDelay.cpp
    Actor.cpp
    ActorAnimation.cpp
    ActorBackpack.cpp
    ActorCameras.cpp
    ActorCondition.cpp
    ActorCondition_script.cpp
    ActorEffector.cpp
    ActorEffector_script.cpp
    ActorHelmet.cpp
    ActorInput.cpp
    ActorNightVision.cpp
    actor_communication.cpp
    Actor_Events.cpp
    Actor_Feel.cpp
    actor_input_handler.cpp
    actor_memory.cpp
    Actor_Movement.cpp
    actor_mp_client.cpp
    actor_mp_client_export.cpp
    actor_mp_client_import.cpp
    actor_mp_server.cpp
    actor_mp_server_export.cpp
    actor_mp_server_import.cpp
    actor_mp_state.cpp
    Actor_Network.cpp
    actor_script.cpp
    Actor_Sleep.cpp
    actor_statistic_mgr.cpp
    Actor_Weapon.cpp
    AdvancedDetector.cpp
    agent_corpse_manager.cpp
    agent_enemy_manager.cpp
    agent_explosive_manager.cpp
    agent_location_manager.cpp
    agent_manager.cpp
    agent_manager_actions.cpp
    agent_manager_planner.cpp
    agent_manager_properties.cpp
    agent_member_manager.cpp
    agent_memory_manager.cpp
    aimers_base.cpp
    aimers_weapon.cpp
    AI/ai_monsters_misc.cpp
    AI/Crow/ai_crow.cpp
    ai/Monsters/ai_monster_bones.cpp
    ai/Monsters/ai_monster_effector.cpp
    ai/Monsters/ai_monster_motion_stats.cpp
    ai/Monsters/ai_monster_squad.cpp
    ai/Monsters/ai_monster_squad_attack.cpp
    ai/Monsters/ai_monster_squad_manager.cpp
    ai/Monsters/ai_monster_squad_rest.cpp
    ai/Monsters/ai_monster_utils.cpp
    ai/Monsters/anim_triple.cpp
    ai/Monsters/anomaly_detector.cpp
    ai/monsters/anti_aim_ability.cpp
    ai/Monsters/BaseMonster/base_monster.cpp
    ai/Monsters/BaseMonster/base_monster_anim.cpp
    ai/Monsters/BaseMonster/base_monster_debug.cpp
    ai/Monsters/BaseMonster/base_monster_feel.cpp
    ai/Monsters/BaseMonster/base_monster_misc.cpp
    ai/Monsters/BaseMonster/base_monster_net.cpp
    ai/Monsters/BaseMonster/base_monster_path.cpp
    ai/Monsters/BaseMonster/base_monster_script.cpp
    ai/Monsters/BaseMonster/base_monster_startup.cpp
    ai/Monsters/BaseMonster/base_monster_think.cpp
    ai/Monsters/Bloodsucker/bloodsucker.cpp
    ai/Monsters/Bloodsucker/bloodsucker_alien.cpp
    ai/Monsters/Bloodsucker/bloodsucker_script.cpp
    ai/Monsters/Bloodsucker/bloodsucker_state_manager.cpp
    ai/Monsters/Bloodsucker/bloodsucker_vampire_effector.cpp
    ai/Monsters/Boar/boar.cpp
    ai/Monsters/Boar/boar_script.cpp
    ai/Monsters/Boar/boar_state_manager.cpp
    ai/Monsters/Burer/burer.cpp
    ai/Monsters/Burer/burer_fast_gravi.cpp
    ai/Monsters/Burer/burer_script.cpp
    ai/Monsters/Burer/burer_state_manager.cpp
    ai/Monsters/Cat/cat.cpp
    ai/Monsters/Cat/cat_script.cpp
    ai/Monsters/Cat/cat_state_manager.cpp
    ai/Monsters/Chimera/chimera.cpp
    ai/Monsters/Chimera/chimera_script.cpp
    ai/Monsters/Chimera/chimera_state_manager.cpp
    ai/Monsters/controlled_actor.cpp
    ai/Monsters/Controller/controller.cpp
    ai/Monsters/Controller/controller_animation.cpp
    ai/Monsters/Controller/controller_direction.cpp
    ai/Monsters/Controller/controller_psy_hit.cpp
    ai/Monsters/Controller/controller_psy_hit_effector.cpp
    ai/Monsters/Controller/controller_script.cpp
    ai/Monsters/Controller/controller_state_manager.cpp
    ai/Monsters/control_animation.cpp
    ai/Monsters/control_animation_base.cpp
    ai/Monsters/control_animation_base_accel.cpp
    ai/Monsters/control_animation_base_load.cpp
    ai/Monsters/control_animation_base_update.cpp
    ai/Monsters/control_critical_wound.cpp
    ai/Monsters/control_direction.cpp
    ai/Monsters/control_direction_base.cpp
    ai/Monsters/control_jump.cpp
    ai/Monsters/control_manager.cpp
    ai/Monsters/control_manager_custom.cpp
    ai/Monsters/control_melee_jump.cpp
    ai/Monsters/control_movement.cpp
    ai/Monsters/control_movement_base.cpp
    ai/Monsters/control_path_builder.cpp
    ai/Monsters/control_path_builder_base.cpp
    ai/Monsters/control_path_builder_base_path.cpp
    ai/Monsters/control_path_builder_base_set.cpp
    ai/Monsters/control_path_builder_base_update.cpp
    ai/Monsters/control_rotation_jump.cpp
    ai/Monsters/control_run_attack.cpp
    ai/Monsters/control_sequencer.cpp
    ai/Monsters/control_threaten.cpp
    ai/Monsters/corpse_cover.cpp
    ai/Monsters/Dog/dog.cpp
    ai/Monsters/Dog/dog_script.cpp
    ai/Monsters/Dog/dog_state_manager.cpp
    ai/Monsters/energy_holder.cpp
    ai/Monsters/Flesh/flesh.cpp
    ai/Monsters/Flesh/flesh_script.cpp
    ai/Monsters/Flesh/flesh_state_manager.cpp
    ai/Monsters/Fracture/fracture.cpp
    ai/Monsters/Fracture/fracture_script.cpp
    ai/Monsters/Fracture/fracture_state_manager.cpp
    ai/Monsters/invisibility.cpp
    ai/Monsters/melee_checker.cpp
    ai/monsters/monster_aura.cpp
    ai/Monsters/monster_corpse_manager.cpp
    ai/Monsters/monster_corpse_memory.cpp
    ai/Monsters/monster_cover_manager.cpp
    ai/Monsters/monster_enemy_manager.cpp
    ai/Monsters/monster_enemy_memory.cpp
    ai/Monsters/monster_event_manager.cpp
    ai/Monsters/monster_hit_memory.cpp
    ai/Monsters/monster_home.cpp
    ai/Monsters/monster_morale.cpp
    ai/Monsters/monster_sound_memory.cpp
    ai/Monsters/Poltergeist/poltergeist.cpp
    ai/Monsters/Poltergeist/poltergeist_ability.cpp
    ai/Monsters/Poltergeist/poltergeist_flame_thrower.cpp
    ai/Monsters/Poltergeist/poltergeist_movement.cpp
    ai/Monsters/Poltergeist/poltergeist_script.cpp
    ai/Monsters/Poltergeist/poltergeist_state_manager.cpp
    ai/Monsters/Poltergeist/poltergeist_telekinesis.cpp
    ai/Monsters/Pseudodog/pseudodog.cpp
    ai/Monsters/Pseudodog/pseudodog_psi_effector.cpp
    ai/Monsters/Pseudodog/pseudodog_script.cpp
    ai/Monsters/Pseudodog/pseudodog_state_manager.cpp
    ai/Monsters/Pseudodog/psy_dog.cpp
    ai/Monsters/Pseudodog/psy_dog_aura.cpp
    ai/Monsters/Pseudodog/psy_dog_state_manager.cpp
    ai/Monsters/PseudoGigant/pseudogigant_script.cpp
    ai/Monsters/PseudoGigant/pseudogigant_state_manager.cpp
    ai/Monsters/PseudoGigant/pseudo_gigant.cpp
    ai/Monsters/PseudoGigant/pseudo_gigant_step_effector.cpp
    ai/Monsters/psy_aura.cpp
    ai/monsters/rats/ai_rat.cpp
    ai/monsters/rats/ai_rat_animations.cpp
    ai/monsters/rats/ai_rat_behaviour.cpp
    ai/monsters/rats/ai_rat_feel.cpp
    ai/monsters/rats/ai_rat_fire.cpp
    ai/monsters/rats/ai_rat_templates.cpp
    ai/monsters/rats/rat_state_activation.cpp
    ai/monsters/rats/rat_state_initialize.cpp
    ai/monsters/rats/rat_state_switch.cpp
    ai/Monsters/Snork/snork.cpp
    ai/Monsters/Snork/snork_jump.cpp
    ai/Monsters/Snork/snork_script.cpp
    ai/Monsters/Snork/snork_state_manager.cpp
    ai/Monsters/telekinesis.cpp
    ai/Monsters/telekinetic_object.cpp
    ai/Monsters/Tushkano/tushkano.cpp
    ai/Monsters/Tushkano/tushkano_script.cpp
    ai/Monsters/Tushkano/tushkano_state_manager.cpp
    ai/Monsters/Zombie/zombie.cpp
    ai/Monsters/Zombie/zombie_script.cpp
    ai/Monsters/Zombie/zombie_state_manager.cpp
    ai/phantom/phantom.cpp
    Ai/Stalker/ai_stalker.cpp
    ai/stalker/ai_stalker_cover.cpp
    ai/stalker/ai_stalker_debug.cpp
    Ai/Stalker/ai_stalker_events.cpp
    Ai/Stalker/ai_stalker_feel.cpp
    Ai/Stalker/ai_stalker_fire.cpp
    Ai/Stalker/ai_stalker_misc.cpp
    Ai/Stalker/ai_stalker_script.cpp
    ai/stalker/ai_stalker_script_entity.cpp
    Ai/Trader/ai_trader.cpp
    ai/trader/ai_trader_script.cpp
    ai/trader/trader_animation.cpp
    ai/weighted_random.cpp
    ai_crow_script.cpp
    ai_debug_variables.cpp
    ai_obstacle.cpp
    AI_PhraseDialogManager.cpp
    ai_sounds.cpp
    ai_space.cpp
    ai_stalker_alife.cpp
    alife_anomalous_zone.cpp
    alife_combat_manager.cpp
    alife_communication_manager.cpp
    alife_creature_abstract.cpp
    alife_dynamic_object.cpp
    alife_graph_registry.cpp
    alife_group_abstract.cpp
    alife_group_registry.cpp
    alife_human_abstract.cpp
    alife_human_brain_script.cpp
    alife_human_object_handler.cpp
    alife_interaction_manager.cpp
    alife_monster_abstract.cpp
    alife_monster_base.cpp
    alife_monster_brain_script.cpp
    alife_monster_detail_path_manager.cpp
    alife_monster_detail_path_manager_script.cpp
    alife_monster_movement_manager.cpp
    alife_monster_movement_manager_script.cpp
    alife_monster_patrol_path_manager.cpp
    alife_monster_patrol_path_manager_script.cpp
    alife_object.cpp
    alife_object_registry.cpp
    alife_online_offline_group.cpp
    alife_online_offline_group_brain.cpp
    alife_registry_container.cpp
    alife_schedule_registry.cpp
    alife_simulator.cpp
    alife_simulator_base.cpp
    alife_simulator_base2.cpp
    alife_simulator_header.cpp
    alife_simulator_script.cpp
    alife_smart_terrain_registry.cpp
    alife_smart_terrain_task.cpp
    alife_smart_terrain_task_script.cpp
    alife_smart_zone.cpp
    alife_spawn_registry.cpp
    alife_spawn_registry_header.cpp
    alife_spawn_registry_spawn.cpp
    alife_storage_manager.cpp
    alife_story_registry.cpp
    alife_surge_manager.cpp
    alife_switch_manager.cpp
    alife_time_manager.cpp
    alife_trader.cpp
    alife_trader_abstract.cpp
    alife_update_manager.cpp
    AmebaZone.cpp
    ammunition_groups.cpp
    animation_movement_controller.cpp
    animation_script_callback.cpp
    animation_utils.cpp
    antirad.cpp
    antirad_script.cpp
    Artefact.cpp
    artefact_activation.cpp
    artefact_script.cpp
    atlas_stalkercoppc_v1.c
    atlas_submit_queue.cpp
    attachable_item.cpp
    attachment_owner.cpp
    autosave_manager.cpp
    awards_store.cpp
    base_client_classes_script.cpp
    BastArtifact.cpp
    best_scores_helper.cpp
    best_scores_store.cpp
    BlackDrops.cpp
    BlackGraviArtifact.cpp
    black_list.cpp
    Bolt.cpp
    BoneProtections.cpp
    bone_groups.cpp
    BottleItem.cpp
    BottleItem_script.cpp
    BreakableObject.cpp
    CameraEffector.cpp
    CameraFirstEye.cpp
    cameralook.cpp
    Car.cpp
    CarCameras.cpp
    CarDamageParticles.cpp
    CarDoors.cpp
    CarExhaust.cpp
    CarInput.cpp
    CarLights.cpp
    CarScript.cpp
    CarSound.cpp
    CarWeapon.cpp
    CarWheels.cpp
    car_memory.cpp
    cdkey_ban_list.cpp
    CharacterPhysicsSupport.cpp
    character_community.cpp
    character_hit_animations.cpp
    character_rank.cpp
    character_reputation.cpp
    character_shell_control.cpp
    client_spawn_manager.cpp
    client_spawn_manager_script.cpp
    ClimableObject.cpp
    configs_common.cpp
    configs_dumper.cpp
    configs_dump_verifyer.cpp
    console_commands.cpp
    console_commands_mp.cpp
    console_registrator_script.cpp
    cover_evaluators.cpp
    cover_manager.cpp
    cover_point_script.cpp
    cta_game_artefact.cpp
    cta_game_artefact_activation.cpp
    CustomDetector.cpp
    CustomDevice.cpp
    CustomMonster.cpp
    CustomMonster_VCPU.cpp
    CustomOutfit.cpp
    CustomOutfit_script.cpp
    CustomRocket.cpp
    CustomZone.cpp
    CustomZone_script.cpp
    DamagableItem.cpp
    damage_manager.cpp
    danger_cover_location.cpp
    danger_explosive.cpp
    danger_location.cpp
    danger_manager.cpp
    danger_object.cpp
    danger_object_location.cpp
    date_time.cpp
    DBG_Car.cpp
    dbg_draw_frustum.cpp
    death_anims.cpp
    death_anims_predicates.cpp
    debug_make_final_test.cpp
    debug_renderer.cpp
    debug_text_tree.cpp
    DelayedActionFuse.cpp
    DemoInfo.cpp
    DemoInfo_Loader.cpp
    DemoPLay_Control.cpp
    DestroyablePhysicsObject.cpp
    detail_path_manager.cpp
    detail_path_manager_smooth.cpp
    doors_actor.cpp
    doors_door.cpp
    doors_manager.cpp
    Dosimeter.cpp
    double_shot_double_kill.cpp
    DummyArtifact.cpp
    dynamic_obstacles_avoider.cpp
    eatable_item.cpp
    eatable_item_object.cpp
    eatable_item_script.cpp
    EffectorBobbing.cpp
    EffectorFall.cpp
    EffectorShot.cpp
    EffectorShotX.cpp
    EffectorZoomInertion.cpp
    ef_pattern.cpp
    ef_primary.cpp
    ef_storage.cpp
    ef_storage_script.cpp
    ElectricBall.cpp
    EliteDetector.cpp
    encyclopedia_article.cpp
    enemy_manager.cpp
    Entity.cpp
    EntityCondition.cpp
    entity_alive.cpp
    event_conditions_collection.cpp
    ExoOutfit.cpp
    Explosive.cpp
    ExplosiveItem.cpp
    ExplosiveRocket.cpp
    ExplosiveScript.cpp
    F1.cpp
    FadedBall.cpp
    faster_than_bullets_time.cpp
    filereceiver_node.cpp
    filetransfer_node.cpp
    file_transfer.cpp
    fire_disp_controller.cpp
    first_bullet_controller.cpp
    flare.cpp
    Flashlight.cpp
    FoodItem.cpp
    FoodItem_script.cpp
    FryupZone.cpp
    fs_registrator_script.cpp
    GalantineArtifact.cpp
    GameObject.cpp
    GamePersistent.cpp
    gamespy/CdkeyDecode/base32.c
    gamespy/CdkeyDecode/cdkeydecode.c
    GameTask.cpp
    GametaskManager.cpp
    GameTask_script.cpp
    game_base.cpp
    game_cl_artefacthunt.cpp
    game_cl_base.cpp
    game_cl_base_weapon_usage_statistic.cpp
    game_cl_base_weapon_usage_statistic_save.cpp
    game_cl_capturetheartefact_buywnd.cpp
    game_cl_capture_the_artefact.cpp
    game_cl_capture_the_artefact_captions_manager.cpp
    game_cl_capture_the_artefact_messages_menu.cpp
    game_cl_deathmatch.cpp
    game_cl_deathmatch_buywnd.cpp
    game_cl_mp.cpp
    game_cl_mp_messages_menu.cpp
    game_cl_mp_snd_messages.cpp
    game_cl_single.cpp
    game_cl_teamdeathmatch.cpp
    game_graph_script.cpp
    game_news.cpp
    game_state_accumulator.cpp
    game_state_accumulator_state_register.cpp
    game_sv_artefacthunt.cpp
    game_sv_artefacthunt_process_event.cpp
    game_sv_base.cpp
    game_sv_base_console_vars.cpp
    game_sv_capture_the_artefact.cpp
    game_sv_capture_the_artefact_buy_event.cpp
    game_sv_capture_the_artefact_myteam_impl.cpp
    game_sv_capture_the_artefact_process_event.cpp
    game_sv_deathmatch.cpp
    game_sv_deathmatch_process_event.cpp
    game_sv_event_queue.cpp
    game_sv_item_respawner.cpp
    game_sv_mp.cpp
    game_sv_single.cpp
    game_sv_teamdeathmatch.cpp
    game_sv_teamdeathmatch_process_event.cpp
    GlobalFeelTouch.cpp
    GraviArtifact.cpp
    GraviZone.cpp
    Grenade.cpp
    GrenadeLauncher.cpp
    group_hierarchy_holder.cpp
    gsc_dsigned_ltx.cpp
    HairsZone.cpp
    HairsZone_script.cpp
    HangingLamp.cpp
    harvest_time.cpp
    Helicopter.cpp
    Helicopter2.cpp
    HelicopterMovementManager.cpp
    HelicopterWeapon.cpp
    helicopter_script.cpp
    Hit.cpp
    HitMarker.cpp
    hits_store.cpp
    hit_immunity.cpp
    hit_memory_manager.cpp
    holder_custom.cpp
    holder_custom_script.cpp
    HUDCrosshair.cpp
    HudItem.cpp
    HUDManager.cpp
    HUDRecon.cpp
    HudSound.cpp
    HUDTarget.cpp
    hud_item_object.cpp
    IKFoot.cpp
    IKLimbsController.cpp
    Ik/aint.cxx
    Ik/Dof7control.cpp
    Ik/eqn.cxx
    Ik/eulersolver.cxx
    Ik/IKLimb.cpp
    Ik/jtlimits.cxx
    Ik/limb.cxx
    Ik/math3d.cpp
    Ik/mathTrig.cpp
    ik_anim_state.cpp
    ik_calculate_data.cpp
    ik_dbg_matrix.cpp
    ik_foot_collider.cpp
    ik_limb_state.cpp
    ik_object_shift.cpp
    script_imgui_script.cpp
    imotion_position.cpp
    imotion_velocity.cpp
    InfoDocument.cpp
    InfoPortion.cpp
    interactive_animation.cpp
    interactive_motion.cpp
    Inventory.cpp
    InventoryBox.cpp
    InventoryBox_script.cpp
    InventoryOwner.cpp
    InventoryOwner_script.cpp
    inventory_item.cpp
    inventory_item_object.cpp
    inventory_item_script.cpp
    inventory_item_upgrade.cpp
    inventory_owner_info.cpp
    inventory_quickswitch.cpp
    inventory_upgrade.cpp
    inventory_upgrade_base.cpp
    inventory_upgrade_group.cpp
    inventory_upgrade_manager.cpp
    inventory_upgrade_property.cpp
    inventory_upgrade_root.cpp
    invincible_fury.cpp
    item_manager.cpp
    key_binding_registrator_script.cpp
    killer_victim_velocity_angle.cpp
    kills_store.cpp
    Level.cpp
    LevelDebugScript.cpp
    Level_Bullet_Manager.cpp
    Level_bullet_manager_firetrace.cpp
    level_changer.cpp
    level_debug.cpp
    Level_GameSpy_Funcs.cpp
    level_graph.cpp
    level_graph_debug.cpp
    level_graph_debug2.cpp
    level_graph_vertex.cpp
    Level_input.cpp
    Level_load.cpp
    level_map_locations.cpp
    Level_network.cpp
    Level_network_compressed_updates.cpp
    Level_network_Demo.cpp
    Level_network_digest_computer.cpp
    Level_network_map_sync.cpp
    Level_network_messages.cpp
    Level_network_spawn.cpp
    Level_network_start_client.cpp
    level_script.cpp
    Level_secure_messaging.cpp
    Level_SLS_Default.cpp
    Level_SLS_Load.cpp
    Level_SLS_Save.cpp
    level_sounds.cpp
    Level_start.cpp
    location_manager.cpp
    login_manager.cpp
    login_manager_script.cpp
    magic_box3.cpp
    magic_minimize_1d.cpp
    MainMenu.cpp
    map_location.cpp
    map_manager.cpp
    map_spot.cpp
    material_manager.cpp
    medkit.cpp
    medkit_script.cpp
    memory_manager.cpp
    memory_space_script.cpp
    MercuryBall.cpp
    Message_Filter.cpp
    MilitaryOutfit.cpp
    Mincer.cpp
    mincer_script.cpp
    min_obb.cpp
    Missile.cpp
    monster_community.cpp
    MosquitoBald.cpp
    MosquitoBald_script.cpp
    movement_manager.cpp
    movement_manager_game.cpp
    movement_manager_level.cpp
    movement_manager_patrol.cpp
    movement_manager_physic.cpp
    moving_bones_snd_player.cpp
    moving_object.cpp
    moving_objects.cpp
    moving_objects_dynamic.cpp
    moving_objects_dynamic_collision.cpp
    moving_objects_static.cpp
    mpactor_dump_impl.cpp
    MPPlayersBag.cpp
    mp_config_sections.cpp
    Needles.cpp
    NoGravityZone.cpp
    object_actions.cpp
    object_handler.cpp
    object_handler_planner.cpp
    object_handler_planner_missile.cpp
    object_handler_planner_weapon.cpp
    object_property_evaluators.cpp
    obstacles_query.cpp
    ParticlesObject.cpp
    ParticlesPlayer.cpp
    particle_params.cpp
    particle_params_script.cpp
    patrol_path.cpp
    patrol_path_manager.cpp
    patrol_path_params.cpp
    patrol_path_params_script.cpp
    patrol_path_storage.cpp
    patrol_point.cpp
    PDA.cpp
    PHCollisionDamageReceiver.cpp
    PHCommander.cpp
    PHDebug.cpp
    PHDestroyable.cpp
    PHDestroyableNotificate.cpp
    PHMovementControl.cpp
    PHMovementDynamicActivate.cpp
    Phrase.cpp
    PhraseDialog.cpp
    PhraseDialogManager.cpp
    PhraseDialog_script.cpp
    PhraseScript.cpp
    PHScriptCall.cpp
    PHShellCreator.cpp
    PHSimpleCalls.cpp
    PHSimpleCallsScript.cpp
    PHSkeleton.cpp
    PHSoundPlayer.cpp
    PhysicObject.cpp
    PhysicObject_script.cpp
    PhysicsGamePars.cpp
    PhysicsShellHolder.cpp
    PhysicsSkeletonObject.cpp
    physics_element_scripted.cpp
    physics_game.cpp
    physics_joint_scripted.cpp
    physics_shell_animated.cpp
    physics_shell_scripted.cpp
    physics_world_scripted.cpp
    physic_item.cpp
    player_account.cpp
    player_hud.cpp
    player_hud_script.cpp
    player_hud_tune.cpp
    player_name_modifyer.cpp
    player_spot_params.cpp
    player_state_achilles_heel.cpp
    player_state_ambassador.cpp
    player_state_ammo_elapsed.cpp
    player_state_avenger.cpp
    player_state_blitzkrieg.cpp
    player_state_cherub.cpp
    player_state_climber.cpp
    player_state_mad.cpp
    player_state_marksman.cpp
    player_state_multichampion.cpp
    player_state_opener.cpp
    player_state_params.cpp
    player_state_remembrance.cpp
    player_state_skewer.cpp
    player_state_toughy.cpp
    player_team_win_score.cpp
    poses_blending.cpp
    pose_extrapolation.cpp
    PostprocessAnimator.cpp
    pp_effector_custom.cpp
    pp_effector_distance.cpp
    profile_data_types.cpp
    profile_data_types_script.cpp
    profile_store.cpp
    profile_store_script.cpp
    property_evaluator_script.cpp
    property_storage_script.cpp
    purchase_list.cpp
    RadioactiveZone.cpp
    random32.cpp
    rat_states.cpp
    rat_state_base.cpp
    rat_state_manager.cpp
    raypick.cpp
    RegistryFuncs.cpp
    relation_registry.cpp
    relation_registry_actions.cpp
    relation_registry_fights.cpp
    restricted_object.cpp
    restricted_object_obstacle.cpp
    rewarding_events_handlers.cpp
    rewarding_state_events.cpp
    reward_event_generator.cpp
    reward_manager.cpp
    RGD5.cpp
    RocketLauncher.cpp
    RustyHairArtifact.cpp
    saved_game_wrapper.cpp
    saved_game_wrapper_script.cpp
    ScientificOutfit.cpp
    Scope.cpp
    screenshots_common.cpp
    screenshots_writer.cpp
    screenshot_manager.cpp
    screenshot_server.cpp
    ScriptXMLInit.cpp
    script_abstract_action.cpp
    script_action_condition.cpp
    script_action_condition_script.cpp
    script_action_planner_action_wrapper.cpp
    script_action_planner_wrapper.cpp
    script_action_wrapper.cpp
    script_animation_action.cpp
    script_animation_action_script.cpp
    script_attachment_manager.cpp
    script_attachment_script.cpp
    script_binder.cpp
    script_binder_object.cpp
    script_binder_object_script.cpp
    script_binder_object_wrapper.cpp
    script_effector.cpp
    script_effector_script.cpp
    script_effector_wrapper.cpp
    script_engine_help.cpp
    script_entity.cpp
    script_entity_action.cpp
    script_entity_action_script.cpp
    script_game_object.cpp
    script_game_object2.cpp
    script_game_object3.cpp
    script_game_object4.cpp
    script_game_object_inventory_owner.cpp
    script_game_object_script.cpp
    script_game_object_script2.cpp
    script_game_object_script3.cpp
    script_game_object_script_trader.cpp
    script_game_object_smart_covers.cpp
    script_game_object_trader.cpp
    script_game_object_use.cpp
    script_game_object_use2.cpp
    script_hit.cpp
    script_hit_script.cpp
    script_lanim.cpp
    script_monster_action.cpp
    script_monster_action_script.cpp
    script_monster_hit_info_script.cpp
    script_movement_action.cpp
    script_movement_action_script.cpp
    script_object.cpp
    script_object_action.cpp
    script_object_action_script.cpp
    script_particles.cpp
    script_particles_script.cpp
    script_particle_action.cpp
    script_particle_action_script.cpp
    script_property_evaluator_wrapper.cpp
    script_render_device_script.cpp
    script_sound.cpp
    script_sound_action.cpp
    script_sound_action_script.cpp
    script_sound_info_script.cpp
    script_sound_script.cpp
    script_wallmarks_manager.cpp
    script_wallmarks_script.cpp
    script_watch_action.cpp
    script_watch_action_script.cpp
    script_world_property_script.cpp
    script_world_state_script.cpp
    script_zone.cpp
    script_zone_script.cpp
    searchlight.cpp
    secure_messaging.cpp
    seniority_hierarchy_holder.cpp
    server_entity_wrapper.cpp
    script_light_script.cpp
    ShootingObject.cpp
    shootingObject_dump_impl.cpp
    sight_action.cpp
    sight_manager.cpp
    sight_manager_target.cpp
    Silencer.cpp
    silent_shots.cpp
    SimpleDetector.cpp
    smart_cover.cpp
    smart_cover_action.cpp
    smart_cover_animation_planner.cpp
    smart_cover_animation_selector.cpp
    smart_cover_default_behaviour_planner.cpp
    smart_cover_description.cpp
    smart_cover_detail.cpp
    smart_cover_evaluators.cpp
    smart_cover_loophole.cpp
    smart_cover_loophole_planner_actions.cpp
    smart_cover_object.cpp
    smart_cover_object_script.cpp
    smart_cover_planner_actions.cpp
    smart_cover_planner_target_provider.cpp
    smart_cover_planner_target_selector.cpp
    smart_cover_storage.cpp
    smart_cover_transition.cpp
    smart_cover_transition_animation.cpp
    sound_collection_storage.cpp
    sound_memory_manager.cpp
    sound_player.cpp
    space_restriction.cpp
    space_restriction_base.cpp
    space_restriction_bridge.cpp
    space_restriction_composition.cpp
    space_restriction_holder.cpp
    space_restriction_manager.cpp
    space_restriction_shape.cpp
    space_restrictor.cpp
    space_restrictor_script.cpp
    Spectator.cpp
    spectator_camera_first_eye.cpp
    sprinter_stopper.cpp
    squad_hierarchy_holder.cpp
    StalkerOutfit.cpp
    stalker_alife_actions.cpp
    stalker_alife_planner.cpp
    stalker_alife_task_actions.cpp
    stalker_animation_callbacks.cpp
    stalker_animation_data.cpp
    stalker_animation_data_storage.cpp
    stalker_animation_global.cpp
    stalker_animation_head.cpp
    stalker_animation_legs.cpp
    stalker_animation_manager.cpp
    stalker_animation_manager_debug.cpp
    stalker_animation_manager_update.cpp
    stalker_animation_names.cpp
    stalker_animation_pair.cpp
    stalker_animation_script.cpp
    stalker_animation_state.cpp
    stalker_animation_torso.cpp
    stalker_anomaly_actions.cpp
    stalker_anomaly_planner.cpp
    stalker_base_action.cpp
    stalker_combat_actions.cpp
    stalker_combat_action_base.cpp
    stalker_combat_planner.cpp
    stalker_danger_by_sound_actions.cpp
    stalker_danger_by_sound_planner.cpp
    stalker_danger_grenade_actions.cpp
    stalker_danger_grenade_planner.cpp
    stalker_danger_in_direction_actions.cpp
    stalker_danger_in_direction_planner.cpp
    stalker_danger_planner.cpp
    stalker_danger_property_evaluators.cpp
    stalker_danger_unknown_actions.cpp
    stalker_danger_unknown_planner.cpp
    stalker_death_actions.cpp
    stalker_death_planner.cpp
    stalker_flair.cpp
    stalker_get_distance_actions.cpp
    stalker_get_distance_planner.cpp
    stalker_kill_wounded_actions.cpp
    stalker_kill_wounded_planner.cpp
    stalker_low_cover_actions.cpp
    stalker_low_cover_planner.cpp
    stalker_movement_manager_base.cpp
    stalker_movement_manager_obstacles.cpp
    stalker_movement_manager_obstacles_path.cpp
    stalker_movement_manager_smart_cover.cpp
    stalker_movement_manager_smart_cover_fov_range.cpp
    stalker_movement_manager_smart_cover_loopholes.cpp
    stalker_movement_params.cpp
    stalker_planner.cpp
    stalker_property_evaluators.cpp
    stalker_search_actions.cpp
    stalker_search_planner.cpp
    stalker_sound_data.cpp
    stalker_sound_data_visitor.cpp
    stalker_velocity_collection.cpp
    stalker_velocity_holder.cpp
    state_arguments_functions.cpp
    static_obstacles_avoider.cpp
    stats_submitter.cpp
    stats_submitter_dsa_params.cpp
    steering_behaviour.cpp
    StdAfx.cpp
    step_manager.cpp
    string_table.cpp
    team_base_zone.cpp
    team_hierarchy_holder.cpp
    TeleWhirlwind.cpp
    ThornArtifact.cpp
    Torch.cpp
    torch_script.cpp
    TorridZone.cpp
    Tracer.cpp
    trade.cpp
    trade2.cpp
    trade_parameters.cpp
    traffic_optimization.cpp
    trajectories.cpp
    UIAchivementsIndicator.cpp
    UICursor.cpp
    UIDialogHolder.cpp
    UIDosimeter.cpp
    UIGameAHunt.cpp
    UIGameCTA.cpp
    UIGameCustom.cpp
    UIGameCustom_script.cpp
    UIGameDM.cpp
    UIGameMP.cpp
    UIGameSP.cpp
    UIGameTDM.cpp
    UIPanelsClassFactory.cpp
    UIPlayerItem.cpp
    UIStaticItem.cpp
    UITeamHeader.cpp
    UITeamPanels.cpp
    UITeamState.cpp
    UIZoneMap.cpp
    ui/ArtefactDetectorUI.cpp
    ui/map_hint.cpp
    ui/MMSound.cpp
    ui/Restrictions.cpp
    ui/ServerList.cpp
    ui/ServerList_GameSpy_func.cpp
    ui/TeamInfo.cpp
    ui/UI3tButton.cpp
    ui/UIAchievements.cpp
    ui/UIRankingsCoC.cpp
    ui/UIActorMenu.cpp
    ui/UIActorMenuDeadBodySearch.cpp
    ui/UIActorMenuInitialize.cpp
    ui/UIActorMenuInventory.cpp
    ui/UIActorMenuTrade.cpp
    ui/UIActorMenuUpgrade.cpp
    ui/UIActorMenu_action.cpp
    ui/UIActorMenu_script.cpp
    ui/UIActorStateInfo.cpp
    ui/UIAnimatedStatic.cpp
    ui/UIBoosterInfo.cpp
    ui/UIBtnHint.cpp
    ui/UIButton.cpp
    ui/UIButton_script.cpp
    ui/UIBuyWeaponTab.cpp
    ui/UIBuyWndShared.cpp
    ui/UICarPanel.cpp
    ui/UICDkey.cpp
    ui/UICellCustomItems.cpp
    ui/UICellItem.cpp
    ui/UICellItemFactory.cpp
    ui/UIChangeMap.cpp
    ui/ChangeWeatherDialog.cpp
    ui/UICharacterInfo.cpp
    ui/UIChatWnd.cpp
    ui/UICheckButton.cpp
    ui/UIComboBox.cpp
    ui/UIComboBox_script.cpp
    ui/UICustomEdit.cpp
    ui/UICustomSpin.cpp
    ui/UIDemoPlayControl.cpp
    ui/UIDialogWnd.cpp
    ui/UIDoubleProgressBar.cpp
    ui/UIDragDropListEx.cpp
    ui/UIDragDropReferenceList.cpp
    ui/UIEditBox.cpp
    ui/UIEditBoxEx.cpp
    ui/UIEditBox_script.cpp
    ui/UIEditKeyBind.cpp
    ui/UIFixedScrollBar.cpp
    ui/UIFrameLineWnd.cpp
    ui/UIFrameWindow.cpp
    ui/UIGameLog.cpp
    ui/UIGameTutorial.cpp
    ui/UIGameTutorialSimpleItem.cpp
    ui/UIGameTutorialVideoItem.cpp
    ui/UIHelper.cpp
    ui/UIHint.cpp
    ui/UIHudStatesWnd.cpp
    ui/UIInventoryUpgradeWnd.cpp
    ui/UIInventoryUpgradeWnd_add.cpp
    ui/UIInventoryUtilities.cpp
    ui/UIInvUpgrade.cpp
    ui/UIInvUpgradeInfo.cpp
    ui/UIInvUpgradeProperty.cpp
    ui/UIItemInfo.cpp
    ui/UIKeyBinding.cpp
    ui/UIKickPlayer.cpp
    ui/UILanimController.cpp
    ui/UILine.cpp
    ui/UILines.cpp
    ui/UIListBox.cpp
    ui/UIListBoxItem.cpp
    ui/UIListBoxItemMsgChain.cpp
    ui/UIListBox_script.cpp
    ui/UIListItemServer.cpp
    ui/UILogsWnd.cpp
    ui/UIMainIngameWnd.cpp
    ui/UIMap.cpp
    ui/UIMapDesc.cpp
    ui/UIMapInfo.cpp
    ui/UIMapInfo_script.cpp
    ui/UIMapLegend.cpp
    ui/UIMapList.cpp
    ui/UIMapWnd.cpp
    ui/UIMapWnd2.cpp
    ui/UIMapWndActions.cpp
    ui/UIMessageBox.cpp
    ui/UIMessageBoxEx.cpp
    ui/UIMessageBox_script.cpp
    ui/UIMessagesWindow.cpp
    ui/UIMMShniaga.cpp
    ui/UIMoneyIndicator.cpp
    ui/UIMotionIcon.cpp
    ui/UIMPAdminMenu.cpp
    ui/UIMPChangeMapAdm.cpp
    ui/UIMpItemsStoreWnd.cpp
    ui/UIMPPlayersAdm.cpp
    ui/UIMPServerAdm.cpp
    ui/UIMpTradeWnd.cpp
    ui/UIMpTradeWnd_init.cpp
    ui/UIMpTradeWnd_items.cpp
    ui/UIMpTradeWnd_misc.cpp
    ui/UIMpTradeWnd_trade.cpp
    ui/UIMpTradeWnd_wpn.cpp
    ui/UINewsItemWnd.cpp
    ui/UIOptConCom.cpp
    ui/UIOptionsItem.cpp
    ui/UIOptionsManager.cpp
    ui/UIOptionsManagerScript.cpp
    ui/UIOutfitInfo.cpp
    ui/UIPdaKillMessage.cpp
    ui/UIPdaMsgListItem.cpp
    ui/UIPdaWnd.cpp
    ui/UIProgressBar.cpp
    ui/UIProgressBar_script.cpp
    ui/UIProgressShape.cpp
    ui/UIPropertiesBox.cpp
    ui/UIPropertiesBox_script.cpp
    ui/UIRadioButton.cpp
    ui/UIRankIndicator.cpp
    ui/UIRankingWnd.cpp
    ui/UIScriptWnd.cpp
    ui/UIScriptWnd_script.cpp
    ui/uiscriptwnd_script2.cpp
    ui/UIScrollBar.cpp
    ui/UIScrollBox.cpp
    ui/UIScrollView.cpp
    ui/UISecondTaskWnd.cpp
    ui/UIServerInfo.cpp
    ui/UISkinSelector.cpp
    ui/UISpawnWnd.cpp
    ui/UISpeechMenu.cpp
    ui/UISpinNum.cpp
    ui/UISpinText.cpp
    ui/UIStatic.cpp
    ui/UIStatic_script.cpp
    ui/UIStatix.cpp
    ui/UIStats.cpp
    ui/UIStatsIcon.cpp
    ui/UIStatsPlayerInfo.cpp
    ui/UIStatsPlayerList.cpp
    ui/UISubLine.cpp
    ui/UITabButton.cpp
    ui/UITabButtonMP.cpp
    ui/UITabControl.cpp
    ui/UITabControl_script.cpp
    ui/UITalkDialogWnd.cpp
    ui/UITalkWnd.cpp
    ui/UITaskWnd.cpp
    ui/UITextureMaster.cpp
    ui/UITextVote.cpp
    ui/UITrackBar.cpp
    ui/UITrackButton.cpp
    ui/UIVote.cpp
    ui/UIVoteStatusWnd.cpp
    ui/UIVotingCategory.cpp
    ui/UIWindow.cpp
    ui/UIWindow_script.cpp
    ui/UIWndCallback.cpp
    ui/UIWpnParams.cpp
    ui/UIXmlInit.cpp
    ui/ui_af_params.cpp
    ui/ui_arrow.cpp
    ui/UI_IB_Static.cpp
    ui/xrUIXmlParser.cpp
    ui_base.cpp
    ui_export_script.cpp
    UsableScriptObject.cpp
    vision_client.cpp
    visual_memory_manager.cpp
    visual_memory_params.cpp
    wallmark_manager.cpp
    Weapon.cpp
    WeaponAK74.cpp
    WeaponAmmo.cpp
    WeaponAmmo_script.cpp
    WeaponAutomaticShotgun.cpp
    WeaponBinoculars.cpp
    WeaponBinocularsVision.cpp
    WeaponBinoculars_script.cpp
    weaponBM16.cpp
    weaponBM16_script.cpp
    WeaponCustomAuto.cpp
    WeaponCustomPistol.cpp
    WeaponDispersion.cpp
    WeaponFire.cpp
    WeaponFN2000.cpp
    WeaponFORT.cpp
    WeaponGroza.cpp
    WeaponHPSA.cpp
    WeaponHPSA_script.cpp
    WeaponKnife.cpp
    WeaponKnife_script.cpp
    WeaponLR300.cpp
    WeaponMagazined.cpp
    WeaponMagazinedWGrenade.cpp
    WeaponMagazineExtended.cpp
    WeaponPistol.cpp
    WeaponPM.cpp
    WeaponRevolver.cpp
    WeaponRG6.cpp
    WeaponRG6_script.cpp
    WeaponRPG7.cpp
    WeaponRPG7_script.cpp
    WeaponShotgun.cpp
    weaponshotgun_script.cpp
    WeaponSSRS.cpp
    WeaponSSRS_script.cpp
    WeaponStatMgun.cpp
    HolderEntityObject.cpp
    WeaponStatMgunFire.cpp
    WeaponStatMgunIR.cpp
    WeaponSVD.cpp
    WeaponSVU.cpp
    WeaponUpgrade.cpp
    WeaponUSP45.cpp
    WeaponVal.cpp
    WeaponVintorez.cpp
    WeaponWalther.cpp
    weapon_ammo_dump_impl.cpp
    weapon_dump_impl.cpp
    Wound.cpp
    xrClientsPool.cpp
    xrGame.cpp
    xrGameSpyServer.cpp
    xrGameSpyServer_callbacks.cpp
    xrGameSpy_GameSpyFuncs.cpp
    xrgame_dll_detach.cpp
    xrServer.cpp
    xrServerMapSync.cpp
    xrServer_balance.cpp
    xrServer_CL_connect.cpp
    xrServer_CL_disconnect.cpp
    xrServer_Connect.cpp
    xrServer_Disconnect.cpp
    xrServer_info.cpp
    xrServer_perform_GameExport.cpp
    xrServer_perform_migration.cpp
    xrServer_perform_RPgen.cpp
    xrServer_perform_sls_default.cpp
    xrServer_perform_sls_load.cpp
    xrServer_perform_sls_save.cpp
    xrServer_perform_transfer.cpp
    xrServer_process_event.cpp
    xrServer_process_event_activate.cpp
    xrServer_process_event_destroy.cpp
    xrServer_process_event_ownership.cpp
    xrServer_process_event_reject.cpp
    xrServer_process_spawn.cpp
    xrServer_process_update.cpp
    xrServer_secure_messaging.cpp
    xrServer_sls_clear.cpp
    xrServer_svclient_validation.cpp
    xrServer_updates_compressor.cpp
    xr_dsa_signer.cpp
    xr_dsa_verifyer.cpp
    xr_level_controller.cpp
    xr_time.cpp
    ZoneCampfire.cpp
    ZoneVisual.cpp
    zone_effector.cpp
    ZudaArtifact.cpp
)

target_include_directories(xrGame
  PRIVATE
  "${CMAKE_CURRENT_SOURCE_DIR}"
  "${CMAKE_CURRENT_SOURCE_DIR}/ai/monsters"
  "${CMAKE_SOURCE_DIR}/src"
  "${CMAKE_SOURCE_DIR}/src/3rd party"
  "${CMAKE_SOURCE_DIR}/src/3rd party/cximage"
  "${CMAKE_SOURCE_DIR}/src/3rd party/luabind"
  "${CMAKE_SOURCE_DIR}/src/3rd party/luajit-2/src"
  "${CMAKE_SOURCE_DIR}/src/xrServerEntities"
  "${CMAKE_SOURCE_DIR}/sdk/include"
)

target_compile_definitions(xrGame
  PUBLIC
  NDEBUG
  XRGAME_EXPORTS
  dSINGLE

  PRIVATE
  WIN32
  MSVC
  _WINDOWS
  _USRDLL
  _SECURE_SCL=0
)

enable_parallel_build(xrGame)
disable_exceptions()
silence_stdext_hash_deprecation_warnings(xrGame)
