add_library(tbb INTERFACE)

target_folder(tbb ${FOLDER_SDK})

target_sources(tbb
  PRIVATE
  compat/condition_variable
  compat/ppl.h
  compat/thread
  compat/tuple

  internal/_aggregator_impl.h
  internal/_allocator_traits.h
  internal/_concurrent_queue_impl.h
  internal/_concurrent_skip_list_impl.h
  internal/_concurrent_unordered_impl.h
  internal/_deprecated_header_message_guard.h
  internal/_flow_graph_async_msg_impl.h
  internal/_flow_graph_body_impl.h
  internal/_flow_graph_cache_impl.h
  internal/_flow_graph_impl.h
  internal/_flow_graph_indexer_impl.h
  internal/_flow_graph_item_buffer_impl.h
  internal/_flow_graph_join_impl.h
  internal/_flow_graph_node_impl.h
  internal/_flow_graph_node_set_impl.h
  internal/_flow_graph_nodes_deduction.h
  internal/_flow_graph_streaming_node.h
  internal/_flow_graph_tagged_buffer_impl.h
  internal/_flow_graph_trace_impl.h
  internal/_flow_graph_types_impl.h
  internal/_mutex_padding.h
  internal/_node_handle_impl.h
  internal/_range_iterator.h
  internal/_tbb_hash_compare_impl.h
  internal/_tbb_strings.h
  internal/_tbb_trace_impl.h
  internal/_tbb_windef.h
  internal/_template_helpers.h
  internal/_warning_suppress_disable_notice.h
  internal/_warning_suppress_enable_notice.h
  internal/_x86_eliding_mutex_impl.h
  internal/_x86_rtm_rw_mutex_impl.h

  machine/gcc_arm.h
  machine/gcc_generic.h
  machine/gcc_ia32_common.h
  machine/gcc_itsx.h
  machine/ibm_aix51.h
  machine/icc_generic.h
  machine/linux_common.h
  machine/linux_ia32.h
  machine/linux_ia64.h
  machine/linux_intel64.h
  machine/mac_ppc.h
  machine/macos_common.h
  machine/mic_common.h
  machine/msvc_armv7.h
  machine/msvc_ia32_common.h
  machine/sunos_sparc.h
  machine/windows_api.h
  machine/windows_ia32.h
  machine/windows_intel64.h

  aggregator.h
  aligned_space.h
  atomic.h
  blocked_range.h
  blocked_range2d.h
  blocked_range3d.h
  blocked_rangeNd.h
  cache_aligned_allocator.h
  CMakeLists.txt
  combinable.h
  concurrent_hash_map.h
  concurrent_lru_cache.h
  concurrent_map.h
  concurrent_priority_queue.h
  concurrent_queue.h
  concurrent_set.h
  concurrent_unordered_map.h
  concurrent_unordered_set.h
  concurrent_vector.h
  critical_section.h
  enumerable_thread_specific.h
  flow_graph.h
  flow_graph_abstractions.h
  flow_graph_opencl_node.h
  global_control.h
  index.html
  info.h
  iterators.h
  memory_pool.h
  mutex.h
  null_mutex.h
  null_rw_mutex.h
  parallel_do.h
  parallel_for.h
  parallel_for_each.h
  parallel_invoke.h
  parallel_reduce.h
  parallel_scan.h
  parallel_sort.h
  parallel_while.h
  partitioner.h
  pipeline.h
  queuing_mutex.h
  queuing_rw_mutex.h
  reader_writer_lock.h
  recursive_mutex.h
  runtime_loader.h
  scalable_allocator.h
  spin_mutex.h
  spin_rw_mutex.h
  task.h
  task_arena.h
  task_group.h
  task_scheduler_init.h
  task_scheduler_observer.h
  tbb.h
  tbb_allocator.h
  tbb_config.h
  tbb_disable_exceptions.h
  tbb_exception.h
  tbb_machine.h
  tbb_profiling.h
  tbb_stddef.h
  tbb_thread.h
  tbbmalloc_proxy.h
  tick_count.h
)

target_include_directories(tbb
  INTERFACE
  ${CMAKE_CURRENT_SOURCE_DIR}/..
)

add_library(tbb_shared SHARED IMPORTED)
set_property(
  TARGET tbb_shared
  PROPERTY IMPORTED_LOCATION
  ${CMAKE_SOURCE_DIR}/sdk/binaries/tbb.dll
)
set_property(
  TARGET tbb_shared
  PROPERTY
  IMPORTED_IMPLIB
  ${CMAKE_SOURCE_DIR}/sdk/libraries/x64.old/tbb.lib
)

target_link_libraries(tbb
  INTERFACE
  tbb_shared
)
