add_subdirectory(crypto)
add_subdirectory(cximage)
add_subdirectory(discord)
add_subdirectory(DXERR)
add_subdirectory(imgui)
add_subdirectory(luabind)
add_subdirectory(lua-extensions)
add_subdirectory(luajit-build)
add_subdirectory(NVTT)
add_subdirectory(ode)
add_subdirectory(openal)
add_subdirectory(reshade)
add_subdirectory(serial)
add_subdirectory(stackwalker)
add_subdirectory(tbb)
