inputs:
  config-preset:
    required: true
  build-preset:
    required: true
  gamedata-target:
    required: false
    default: Gamedata

runs:
  using: composite
  steps:
    - uses: lukka/run-cmake@v10
      with:
        configurePreset: ${{inputs.config-preset}}
        buildPreset: "${{inputs.config-preset}}.${{inputs.build-preset}}"
        buildPresetAdditionalArgs: "['--target ${{inputs.gamedata-target}}']"