runs:
  using: composite

  steps:
    - name: Install
      shell: bash
      run: sudo apt-get install dos2unix recode

    - name: Line Endings / BOM
      shell: bash
      run: |
        # Ensure files have LF line endings and do not contain a BOM
        find . \( -path ./Externals -o -path ./sdk \) -prune -o -iregex '.*\.\(h\|hpp\|inl\|c\|cpp\|yaml\|yml\|md\|txt\|cmake\|sh\)' -type f -exec bash -c 'dos2unix "$0" 2> /dev/null' {} \;

    - name: Report
      uses: ./.github/actions/check-result
      with:
        message-ok: No files contain LF line endings or BOM
        message-error: Contains non-LF line endings or BOM
