add_module(XRay.Game.Scripts
  CHILD_OF XRay.Game

  SOURCES
  script_abstract_action.cpp
  script_action_condition.cpp
  script_action_condition_script.cpp
  script_action_planner_action_wrapper.cpp
  script_action_planner_wrapper.cpp
  script_action_wrapper.cpp
  script_animation_action.cpp
  script_animation_action_script.cpp
  script_attachment_manager.cpp
  script_attachment_script.cpp
  script_binder.cpp
  script_binder_object.cpp
  script_binder_object_script.cpp
  script_binder_object_wrapper.cpp
  script_effector.cpp
  script_effector_script.cpp
  script_effector_wrapper.cpp
  script_engine_help.cpp
  script_entity.cpp
  script_entity_action.cpp
  script_entity_action_script.cpp
  script_game_object.cpp
  script_game_object2.cpp
  script_game_object3.cpp
  script_game_object4.cpp
  script_game_object_inventory_owner.cpp
  script_game_object_script.cpp
  script_game_object_script2.cpp
  script_game_object_script3.cpp
  script_game_object_script_trader.cpp
  script_game_object_smart_covers.cpp
  script_game_object_trader.cpp
  script_game_object_use.cpp
  script_game_object_use2.cpp
  script_hit.cpp
  script_hit_script.cpp
  script_lanim.cpp
  script_monster_action.cpp
  script_monster_action_script.cpp
  script_monster_hit_info_script.cpp
  script_movement_action.cpp
  script_movement_action_script.cpp
  script_object.cpp
  script_object_action.cpp
  script_object_action_script.cpp
  script_particles.cpp
  script_particles_script.cpp
  script_particle_action.cpp
  script_particle_action_script.cpp
  script_property_evaluator_wrapper.cpp
  script_render_device_script.cpp
  script_sound.cpp
  script_sound_action.cpp
  script_sound_action_script.cpp
  script_sound_info_script.cpp
  script_sound_script.cpp
  script_wallmarks_manager.cpp
  script_wallmarks_script.cpp
  script_watch_action.cpp
  script_watch_action_script.cpp
  script_world_property_script.cpp
  script_world_state_script.cpp
  script_zone.cpp
  script_zone_script.cpp
  script_imgui_script.cpp
  script_light_script.cpp

  script_zone.h
  ScriptXMLInit.h
  script_attachment_manager.h
  script_imgui.h
  script_imgui_inline.h
  script_light_inline.h
  script_abstract_action.h
  script_abstract_action_inline.h
  script_action_condition.h
  script_action_condition_inline.h
  script_action_planner_action_wrapper.h
  script_action_planner_action_wrapper_inline.h
  script_action_planner_wrapper.h
  script_action_planner_wrapper_inline.h
  script_action_wrapper.h
  script_action_wrapper_inline.h
  script_animation_action.h
  script_animation_action_inline.h
  script_binder.h
  script_binder_inline.h
  script_binder_object.h
  script_binder_object_wrapper.h
  script_bind_macroses.h
  script_callback_ex.h
  script_callback_ex_generators.h
  script_callback_ex_inline.h
  script_callback_ex_nonvoid.h
  script_callback_ex_void.h
  script_effector.h
  script_effector_inline.h
  script_effector_wrapper.h
  script_effector_wrapper_inline.h
  script_entity.h
  script_entity_action.h
  script_entity_action_inline.h
  script_entity_inline.h
  script_entity_space.h
  script_game_object.h
  script_game_object_impl.h
  script_hit.h
  script_hit_inline.h
  script_lanim.h
  script_light.h
  script_monster_action.h
  script_monster_action_inline.h
  script_monster_hit_info.h
  script_movement_action.h
  script_movement_action_inline.h
  script_object.h
  script_object_action.h
  script_object_action_inline.h
  script_particles.h
  script_particles_inline.h
  script_particle_action.h
  script_particle_action_inline.h
  script_property_evaluator_wrapper.h
  script_property_evaluator_wrapper_inline.h
  script_render_device.h
  script_sound.h
  script_sound_action.h
  script_sound_action_inline.h
  script_sound_info.h
  script_sound_inline.h
  script_ui_registrator.h
  script_wallmarks_manager.h
  script_watch_action.h
  script_watch_action_inline.h
  script_world_property.h
  script_world_property_inline.h
  script_world_state.h
)

target_include_directories(XRay.Game.Scripts
  PUBLIC
  ${CMAKE_CURRENT_SOURCE_DIR}
  PRIVATE
  ${CMAKE_SOURCE_DIR}/src/xrServerEntities
)

target_compile_definitions(XRay.Game.Scripts
  PRIVATE
  XRGAME_EXPORTS
)

target_precompile_headers(XRay.Game.Scripts
  PRIVATE
  $<$<COMPILE_LANGUAGE:CXX>:stdafx.h>
)

target_link_libraries(XRay.Game.Scripts
  PRIVATE
  DPlay
  imgui
  luabind
  LuaJIT
  XRay.Collision
  XRay.Core
  XRay.Engine
  XRay.Render
  XRay.Render.API
  XRay.Physics
  XRay.Sound
  XRay.NetServer
)
