add_library(XRay.Game.UI STATIC)

set_property(
  TARGET XRay.Game.UI
  PROPERTY FOLDER
  ${FOLDER_XRAY_GAME}
)

target_sources(XRay.Game.UI PRIVATE
  UIAchivementsIndicator.cpp
  UICursor.cpp
  UIDialogHolder.cpp
  UIDosimeter.cpp
  UIGameAHunt.cpp
  UIGameCTA.cpp
  UIGameCustom.cpp
  UIGameCustom_script.cpp
  UIGameDM.cpp
  UIGameMP.cpp
  UIGameSP.cpp
  UIGameTDM.cpp
  UIPanelsClassFactory.cpp
  UIPlayerItem.cpp
  UIStaticItem.cpp
  UITeamHeader.cpp
  UITeamPanels.cpp
  UITeamState.cpp
  UIZoneMap.cpp
  ui/ArtefactDetectorUI.cpp
  ui/map_hint.cpp
  ui/MMSound.cpp
  ui/Restrictions.cpp
  ui/ServerList.cpp
  ui/ServerList_GameSpy_func.cpp
  ui/TeamInfo.cpp
  ui/UI3tButton.cpp
  ui/UIAchievements.cpp
  ui/UIRankingsCoC.cpp
  ui/UIActorMenu.cpp
  ui/UIActorMenuDeadBodySearch.cpp
  ui/UIActorMenuInitialize.cpp
  ui/UIActorMenuInventory.cpp
  ui/UIActorMenuTrade.cpp
  ui/UIActorMenuUpgrade.cpp
  ui/UIActorMenu_action.cpp
  ui/UIActorMenu_script.cpp
  ui/UIActorStateInfo.cpp
  ui/UIAnimatedStatic.cpp
  ui/UIBoosterInfo.cpp
  ui/UIBtnHint.cpp
  ui/UIButton.cpp
  ui/UIButton_script.cpp
  ui/UIBuyWeaponTab.cpp
  ui/UIBuyWndShared.cpp
  ui/UICarPanel.cpp
  ui/UICDkey.cpp
  ui/UICellCustomItems.cpp
  ui/UICellItem.cpp
  ui/UICellItemFactory.cpp
  ui/UIChangeMap.cpp
  ui/ChangeWeatherDialog.cpp
  ui/UICharacterInfo.cpp
  ui/UIChatWnd.cpp
  ui/UICheckButton.cpp
  ui/UIComboBox.cpp
  ui/UIComboBox_script.cpp
  ui/UICustomEdit.cpp
  ui/UICustomSpin.cpp
  ui/UIDemoPlayControl.cpp
  ui/UIDialogWnd.cpp
  ui/UIDoubleProgressBar.cpp
  ui/UIDragDropListEx.cpp
  ui/UIDragDropReferenceList.cpp
  ui/UIEditBox.cpp
  ui/UIEditBoxEx.cpp
  ui/UIEditBox_script.cpp
  ui/UIEditKeyBind.cpp
  ui/UIFixedScrollBar.cpp
  ui/UIFrameLineWnd.cpp
  ui/UIFrameWindow.cpp
  ui/UIGameLog.cpp
  ui/UIGameTutorial.cpp
  ui/UIGameTutorialSimpleItem.cpp
  ui/UIGameTutorialVideoItem.cpp
  ui/UIHelper.cpp
  ui/UIHint.cpp
  ui/UIHudstatesWnd.cpp
  ui/UIInventoryUpgradeWnd.cpp
  ui/UIInventoryUpgradeWnd_add.cpp
  ui/UIInventoryUtilities.cpp
  ui/UIInvUpgrade.cpp
  ui/UIInvUpgradeInfo.cpp
  ui/UIInvUpgradeProperty.cpp
  ui/UIItemInfo.cpp
  ui/UIKeyBinding.cpp
  ui/UIKickPlayer.cpp
  ui/UILanimcontroller.cpp
  ui/UILine.cpp
  ui/UILines.cpp
  ui/UIListBox.cpp
  ui/UIListBoxItem.cpp
  ui/UIListBoxItemMsgChain.cpp
  ui/UIListBox_script.cpp
  ui/UIListItemServer.cpp
  ui/UILogsWnd.cpp
  ui/UIMainIngameWnd.cpp
  ui/UIMap.cpp
  ui/UIMapDesc.cpp
  ui/UIMapInfo.cpp
  ui/UIMapInfo_script.cpp
  ui/UIMapLegend.cpp
  ui/UIMapList.cpp
  ui/UIMapWnd.cpp
  ui/UIMapWnd2.cpp
  ui/UIMapWndActions.cpp
  ui/UIMessageBox.cpp
  ui/UIMessageBoxEx.cpp
  ui/UIMessageBox_script.cpp
  ui/UIMessagesWindow.cpp
  ui/UIMMShniaga.cpp
  ui/UIMoneyIndicator.cpp
  ui/UIMotionIcon.cpp
  ui/UIMPAdminMenu.cpp
  ui/UIMPChangeMapAdm.cpp
  ui/UIMpItemsStoreWnd.cpp
  ui/UIMPPlayersAdm.cpp
  ui/UIMPServerAdm.cpp
  ui/UIMpTradeWnd.cpp
  ui/UIMpTradeWnd_init.cpp
  ui/UIMpTradeWnd_items.cpp
  ui/UIMpTradeWnd_misc.cpp
  ui/UIMpTradeWnd_trade.cpp
  ui/UIMpTradeWnd_wpn.cpp
  ui/UINewsItemWnd.cpp
  ui/UIOptConCom.cpp
  ui/UIOptionsItem.cpp
  ui/UIOptionsManager.cpp
  ui/UIOptionsManagerScript.cpp
  ui/UIOutfitInfo.cpp
  ui/UIPdaKillMessage.cpp
  ui/UIPdaMsgListItem.cpp
  ui/UIPdaWnd.cpp
  ui/UIProgressBar.cpp
  ui/UIProgressBar_script.cpp
  ui/UIProgressShape.cpp
  ui/UIPropertiesBox.cpp
  ui/UIPropertiesBox_script.cpp
  ui/UIRadioButton.cpp
  ui/UIRankIndicator.cpp
  ui/UIRankingWnd.cpp
  ui/UIScriptWnd.cpp
  ui/UIScriptWnd_script.cpp
  ui/uiscriptwnd_script2.cpp
  ui/UIScrollBar.cpp
  ui/UIScrollBox.cpp
  ui/UIScrollView.cpp
  ui/UISecondTaskWnd.cpp
  ui/UIServerInfo.cpp
  ui/UISkinSelector.cpp
  ui/UISpawnWnd.cpp
  ui/UISpeechMenu.cpp
  ui/UISpinNum.cpp
  ui/UISpinText.cpp
  ui/UIStatic.cpp
  ui/UIStatic_script.cpp
  ui/UIStatix.cpp
  ui/UIStats.cpp
  ui/UIStatsIcon.cpp
  ui/UIStatsPlayerInfo.cpp
  ui/UIStatsPlayerList.cpp
  ui/UISubLine.cpp
  ui/UITabButton.cpp
  ui/UITabButtonMP.cpp
  ui/UITabControl.cpp
  ui/UITabControl_script.cpp
  ui/UITalkDialogWnd.cpp
  ui/UITalkWnd.cpp
  ui/UITaskWnd.cpp
  ui/UITextureMaster.cpp
  ui/UITextVote.cpp
  ui/UITrackBar.cpp
  ui/UITrackButton.cpp
  ui/UIVote.cpp
  ui/UIVoteStatusWnd.cpp
  ui/UIVotingcategory.cpp
  ui/UIWindow.cpp
  ui/UIWindow_script.cpp
  ui/UIWndCallback.cpp
  ui/UIWpnParams.cpp
  ui/UIXmlInit.cpp
  ui/ui_af_params.cpp
  ui/ui_arrow.cpp
  ui/UI_IB_Static.cpp
  ui/xrUIXmlParser.cpp
  ui_base.cpp
  ui_export_script.cpp

  UIAchivementsIndicator.h
  UICursor.h
  UIDialogHolder.h
  UIDosimeter.h
  UIGameAHunt.h
  UIGameCTA.h
  UIGameCustom.h
  UIGameDM.h
  UIGameMP.h
  UIGameSP.h
  UIGameTDM.h
  UIPanelsClassFactory.h
  UIPlayerItem.h
  UIStaticItem.h
  UITeamHeader.h
  UITeamPanels.h
  UITeamState.h
  UIZoneMap.h
  ui/ArtefactDetectorUI.h
  ui/KillMessageStruct.h
  ui/map_hint.h
  ui/MMSound.h
  ui/Restrictions.h
  ui/ServerList.h
  ui/TeamInfo.h
  ui/UI3tButton.h
  ui/uiabstract.h
  ui/UIAchievements.h
  ui/UIRankingsCoC.h
  ui/UIActorMenu.h
  ui/UIActorStateInfo.h
  ui/UIAnimatedStatic.h
  ui/UIBoosterInfo.h
  ui/UIBtnHint.h
  ui/UIButton.h
  ui/UIBuyWeaponTab.h
  ui/UIBuyWndBase.h
  ui/UIBuyWndShared.h
  ui/UICarPanel.h
  ui/UICDkey.h
  ui/UICellCustomItems.h
  ui/UICellItem.h
  ui/UICellItemFactory.h
  ui/UIChangeMap.h
  ui/ChangeWeatherDialog.hpp
  ui/UICharacterInfo.h
  ui/UIChatWnd.h
  ui/UICheckButton.h
  ui/UIComboBox.h
  ui/UICustomEdit.h
  ui/UICustomSpin.h
  ui/UIDebugFonts.h
  ui/UIDemoPlayControl.h
  ui/UIDialogWnd.h
  ui/UIDoubleProgressBar.h
  ui/UIDragDropListEx.h
  ui/UIDragDropReferenceList.h
  ui/UIEditBox.h
  ui/UIEditBoxEx.h
  ui/UIEditKeyBind.h
  ui/UIFixedScrollBar.h
  ui/UIFrameLineWnd.h
  ui/UIFrameWindow.h
  ui/UIGameLog.h
  ui/UIGameTutorial.h
  ui/UIHelper.h
  ui/UIHint.h
  ui/UIHudstatesWnd.h
  ui/UIInteractiveBackground.h
  ui/UIInventoryUpgradeWnd.h
  ui/UIInventoryUtilities.h
  ui/UIInvUpgrade.h
  ui/UIInvUpgradeInfo.h
  ui/UIInvUpgradeProperty.h
  ui/UIItemInfo.h
  ui/UIKeyBinding.h
  ui/UIKickPlayer.h
  ui/UILanimcontroller.h
  ui/UILine.h
  ui/UILines.h
  ui/uilinestd.h
  ui/UIListBox.h
  ui/UIListBoxItem.h
  ui/UIListBoxItemMsgChain.h
  ui/UIListItemServer.h
  ui/UILogsWnd.h
  ui/UIMainIngameWnd.h
  ui/UIMap.h
  ui/UIMapDesc.h
  ui/UIMapInfo.h
  ui/UIMapLegend.h
  ui/UIMapList.h
  ui/UIMapWnd.h
  ui/UIMapWndActions.h
  ui/UIMapWndActionsSpace.h
  ui/UIMessageBox.h
  ui/UIMessageBoxEx.h
  ui/UIMessages.h
  ui/UIMessagesWindow.h
  ui/UIMMShniaga.h
  ui/UIMoneyIndicator.h
  ui/UIMotionIcon.h
  ui/UIMPAdminMenu.h
  ui/UIMPChangeMapAdm.h
  ui/UIMpItemsStoreWnd.h
  ui/UIMPPlayersAdm.h
  ui/UIMPServerAdm.h
  ui/UIMpTradeWnd.h
  ui/UINewsItemWnd.h
  ui/UIOptConCom.h
  ui/UIOptionsItem.h
  ui/UIOptionsManager.h
  ui/UIOptionsManagerScript.h
  ui/UIOutfitInfo.h
  ui/UIPdaKillMessage.h
  ui/UIPdaMsgListItem.h
  ui/UIPdaWnd.h
  ui/UIProgressBar.h
  ui/UIProgressShape.h
  ui/UIPropertiesBox.h
  ui/UIRadioButton.h
  ui/UIRankIndicator.h
  ui/UIRankingWnd.h
  ui/UIScriptWnd.h
  ui/uiscriptwnd_script.h
  ui/UIScrollBar.h
  ui/UIScrollBox.h
  ui/UIScrollView.h
  ui/UISecondTaskWnd.h
  ui/UIServerInfo.h
  ui/UISkinSelector.h
  ui/UISpawnWnd.h
  ui/UISpeechMenu.h
  ui/UISpinNum.h
  ui/UISpinText.h
  ui/UIStatic.h
  ui/UIStatix.h
  ui/UIStats.h
  ui/UIStatsIcon.h
  ui/UIStatsPlayerInfo.h
  ui/UIStatsPlayerList.h
  ui/UISubLine.h
  ui/UITabButton.h
  ui/UITabButtonMP.h
  ui/UITabControl.h
  ui/UITalkDialogWnd.h
  ui/UITalkWnd.h
  ui/UITaskWnd.h
  ui/UITextureMaster.h
  ui/UITextVote.h
  ui/UITrackBar.h
  ui/UITrackButton.h
  ui/UIVote.h
  ui/UIVoteStatusWnd.h
  ui/UIVotingcategory.h
  ui/UIWindow.h
  ui/UIWndCallback.h
  ui/UIWpnParams.h
  ui/UIXmlInit.h
  ui/ui_af_params.h
  ui/ui_arrow.h
  ui/UI_IB_Static.h
  ui/xrUIXmlParser.h
  ui_base.h
  ui_defs.h
)

target_include_directories(XRay.Game.UI
  PUBLIC
  ${CMAKE_CURRENT_SOURCE_DIR}
  PRIVATE
  ${CMAKE_SOURCE_DIR}/src/xrServerEntities
)

target_precompile_headers(XRay.Game.UI
  PRIVATE
  stdafx.h
)

target_compile_definitions(XRay.Game.UI
  PUBLIC
  XRGAME_EXPORTS
)

target_link_libraries(XRay.Game.UI
  PRIVATE
  CxImage
  DPlay
  luabind
  LuaJIT
  XRay.Collision
  XRay.Core
  XRay.Engine
  XRay.NetServer
  XRay.Physics
  XRay.Render
  XRay.Render.API
)
