add_module(XRay.Game
  INCLUDES
  ${CMAKE_CURRENT_SOURCE_DIR}
  ${CMAKE_SOURCE_DIR}/src/xrServerEntities

  PRECOMPILES $<$<COMPILE_LANGUAGE:CXX>:stdafx.h>
  
  DEFINES XRGAME_EXPORTS

  LINKS
  crypto
  CxImage
  loki
  lua-extensions
  luabind
  LuaJIT
  ode
  XRay.Collision
  XRay.Core
  XRay.Engine
  XRay.NetServer
  XRay.Physics
  XRay.Render
  XRay.Render.API

  SOURCES
  ../xrServerEntities/alife_human_brain.cpp
  ../xrServerEntities/alife_monster_brain.cpp
  ../xrServerEntities/alife_space.cpp
  ../xrServerEntities/character_info.cpp
  ../xrServerEntities/gametype_chooser.cpp
  ../xrServerEntities/LevelGameDef.cpp
  ../xrServerEntities/lua_studio.cpp
  ../xrServerEntities/object_factory.cpp
  ../xrServerEntities/object_factory_register.cpp
  ../xrServerEntities/object_factory_script.cpp
  ../xrServerEntities/object_item_script.cpp
  ../xrServerEntities/pch_script.cpp
  ../xrServerEntities/script_callStack.cpp
  ../xrServerEntities/script_debugger.cpp
  ../xrServerEntities/script_debugger_threads.cpp
  ../xrServerEntities/script_engine.cpp
  ../xrServerEntities/script_engine_export.cpp
  ../xrServerEntities/script_engine_script.cpp
  ../xrServerEntities/script_fcolor_script.cpp
  ../xrServerEntities/script_flags_script.cpp
  ../xrServerEntities/script_fmatrix_script.cpp
  ../xrServerEntities/script_fvector_script.cpp
  ../xrServerEntities/script_ini_file.cpp
  ../xrServerEntities/script_ini_file_script.cpp
  ../xrServerEntities/script_lua_helper.cpp
  ../xrServerEntities/script_net_packet_script.cpp
  ../xrServerEntities/script_process.cpp
  ../xrServerEntities/script_reader_script.cpp
  ../xrServerEntities/script_rtoken_list_script.cpp
  ../xrServerEntities/script_sound_type_script.cpp
  ../xrServerEntities/script_stack_tracker.cpp
  ../xrServerEntities/script_storage.cpp
  ../xrServerEntities/script_thread.cpp
  ../xrServerEntities/script_token_list.cpp
  ../xrServerEntities/script_token_list_script.cpp
  ../xrServerEntities/smart_cast.cpp
  ../xrServerEntities/smart_cast_stats.cpp
  ../xrServerEntities/specific_character.cpp
  ../xrServerEntities/xrServer_Factory.cpp
  ../xrServerEntities/xrServer_Objects.cpp
  ../xrServerEntities/xrServer_Objects_Abstract.cpp
  ../xrServerEntities/xrServer_Objects_ALife.cpp
  ../xrServerEntities/xrServer_Objects_ALife_Items.cpp
  ../xrServerEntities/xrServer_Objects_ALife_Items_script.cpp
  ../xrServerEntities/xrServer_Objects_ALife_Items_script2.cpp
  ../xrServerEntities/xrServer_Objects_ALife_Items_script3.cpp
  ../xrServerEntities/xrServer_Objects_ALife_monsters.cpp
  ../xrServerEntities/xrServer_Objects_ALife_monsters_script.cpp
  ../xrServerEntities/xrServer_Objects_ALife_monsters_script2.cpp
  ../xrServerEntities/xrserver_objects_alife_monsters_script3.cpp
  ../xrServerEntities/xrServer_Objects_ALife_monsters_script4.cpp
  ../xrServerEntities/xrServer_Objects_ALife_script.cpp
  ../xrServerEntities/xrServer_Objects_ALife_script2.cpp
  ../xrServerEntities/xrServer_Objects_ALife_script3.cpp
  ../xrServerEntities/xrServer_Objects_Alife_Smartcovers.cpp
  ../xrServerEntities/xrServer_Objects_Alife_Smartcovers_script.cpp
  ../xrServerEntities/xrServer_Objects_script.cpp
  ../xrServerEntities/xrServer_Objects_script2.cpp
  ../xrServerEntities/xrServer_Object_Base.cpp
  account_manager.cpp
  account_manager_console.cpp
  account_manager_script.cpp
  ActivatingCharCollisionDelay.cpp
  Actor.cpp
  ActorAnimation.cpp
  ActorBackpack.cpp
  ActorCameras.cpp
  ActorCondition.cpp
  ActorCondition_script.cpp
  ActorEffector.cpp
  ActorEffector_script.cpp
  ActorHelmet.cpp
  ActorInput.cpp
  ActorNightVision.cpp
  actor_communication.cpp
  Actor_Events.cpp
  Actor_Feel.cpp
  actor_input_handler.cpp
  actor_memory.cpp
  Actor_Movement.cpp
  actor_mp_client.cpp
  actor_mp_client_export.cpp
  actor_mp_client_import.cpp
  actor_mp_server.cpp
  actor_mp_server_export.cpp
  actor_mp_server_import.cpp
  actor_mp_state.cpp
  Actor_Network.cpp
  actor_script.cpp
  Actor_Sleep.cpp
  actor_statistic_mgr.cpp
  Actor_Weapon.cpp
  AdvancedDetector.cpp
  agent_corpse_manager.cpp
  agent_enemy_manager.cpp
  agent_explosive_manager.cpp
  agent_location_manager.cpp
  agent_manager.cpp
  agent_manager_actions.cpp
  agent_manager_planner.cpp
  agent_manager_properties.cpp
  agent_member_manager.cpp
  agent_memory_manager.cpp
  alife_anomalous_zone.cpp
  alife_combat_manager.cpp
  alife_communication_manager.cpp
  alife_creature_abstract.cpp
  alife_dynamic_object.cpp
  alife_graph_registry.cpp
  alife_group_abstract.cpp
  alife_group_registry.cpp
  alife_human_abstract.cpp
  alife_human_brain_script.cpp
  alife_human_object_handler.cpp
  alife_interaction_manager.cpp
  alife_monster_abstract.cpp
  alife_monster_base.cpp
  alife_monster_brain_script.cpp
  alife_monster_detail_path_manager.cpp
  alife_monster_detail_path_manager_script.cpp
  alife_monster_movement_manager.cpp
  alife_monster_movement_manager_script.cpp
  alife_monster_patrol_path_manager.cpp
  alife_monster_patrol_path_manager_script.cpp
  alife_object.cpp
  alife_object_registry.cpp
  alife_online_offline_group.cpp
  alife_online_offline_group_brain.cpp
  alife_registry_container.cpp
  alife_schedule_registry.cpp
  alife_simulator.cpp
  alife_simulator_base.cpp
  alife_simulator_base2.cpp
  alife_simulator_header.cpp
  alife_simulator_script.cpp
  alife_smart_terrain_registry.cpp
  alife_smart_terrain_task.cpp
  alife_smart_terrain_task_script.cpp
  alife_smart_zone.cpp
  alife_spawn_registry.cpp
  alife_spawn_registry_header.cpp
  alife_spawn_registry_spawn.cpp
  alife_storage_manager.cpp
  alife_story_registry.cpp
  alife_surge_manager.cpp
  alife_switch_manager.cpp
  alife_time_manager.cpp
  alife_trader.cpp
  alife_trader_abstract.cpp
  alife_update_manager.cpp
  AmebaZone.cpp
  ammunition_groups.cpp
  animation_movement_controller.cpp
  animation_script_callback.cpp
  animation_utils.cpp
  antirad.cpp
  antirad_script.cpp
  Artefact.cpp
  artefact_activation.cpp
  artefact_script.cpp
  atlas_stalkercoppc_v1.c
  atlas_submit_queue.cpp
  attachable_item.cpp
  attachment_owner.cpp
  autosave_manager.cpp
  awards_store.cpp
  base_client_classes_script.cpp
  BastArtifact.cpp
  best_scores_helper.cpp
  best_scores_store.cpp
  BlackDrops.cpp
  BlackGraviArtifact.cpp
  black_list.cpp
  Bolt.cpp
  BoneProtections.cpp
  bone_groups.cpp
  BottleItem.cpp
  BottleItem_script.cpp
  BreakableObject.cpp
  CameraEffector.cpp
  CameraFirstEye.cpp
  cameralook.cpp
  Car.cpp
  CarCameras.cpp
  CarDamageParticles.cpp
  CarDoors.cpp
  CarExhaust.cpp
  CarInput.cpp
  CarLights.cpp
  CarScript.cpp
  CarSound.cpp
  CarWeapon.cpp
  CarWheels.cpp
  car_memory.cpp
  cdkey_ban_list.cpp
  CharacterPhysicsSupport.cpp
  character_community.cpp
  character_hit_animations.cpp
  character_rank.cpp
  character_reputation.cpp
  character_shell_control.cpp
  client_spawn_manager.cpp
  client_spawn_manager_script.cpp
  ClimableObject.cpp
  configs_common.cpp
  configs_dumper.cpp
  configs_dump_verifyer.cpp
  console_commands.cpp
  console_commands_mp.cpp
  console_registrator_script.cpp
  cover_evaluators.cpp
  cta_game_artefact.cpp
  cta_game_artefact_activation.cpp
  CustomDetector.cpp
  CustomDevice.cpp
  CustomMonster.cpp
  CustomMonster_VCPU.cpp
  CustomOutfit.cpp
  CustomOutfit_script.cpp
  CustomRocket.cpp
  CustomZone.cpp
  CustomZone_script.cpp
  DamagableItem.cpp
  danger_cover_location.cpp
  danger_explosive.cpp
  danger_location.cpp
  danger_object_location.cpp
  date_time.cpp
  DBG_Car.cpp
  dbg_draw_frustum.cpp
  death_anims.cpp
  death_anims_predicates.cpp
  #debug_make_final_test.cpp
  debug_renderer.cpp
  debug_text_tree.cpp
  DelayedActionFuse.cpp
  DemoInfo.cpp
  DemoInfo_Loader.cpp
  DemoPLay_Control.cpp
  DestroyablePhysicsObject.cpp
  Dosimeter.cpp
  double_shot_double_kill.cpp
  DummyArtifact.cpp
  #DynamicHeightMap.cpp
  dynamic_obstacles_avoider.cpp
  eatable_item.cpp
  eatable_item_object.cpp
  eatable_item_script.cpp
  EffectorBobbing.cpp
  EffectorFall.cpp
  EffectorShot.cpp
  EffectorShotX.cpp
  EffectorZoomInertion.cpp
  ef_pattern.cpp
  ef_primary.cpp
  ef_storage.cpp
  ef_storage_script.cpp
  ElectricBall.cpp
  EliteDetector.cpp
  encyclopedia_article.cpp
  Entity.cpp
  EntityCondition.cpp
  entity_alive.cpp
  event_conditions_collection.cpp
  ExoOutfit.cpp
  Explosive.cpp
  ExplosiveItem.cpp
  ExplosiveRocket.cpp
  ExplosiveScript.cpp
  F1.cpp
  FadedBall.cpp
  faster_than_bullets_time.cpp
  filereceiver_node.cpp
  filetransfer_node.cpp
  file_transfer.cpp
  fire_disp_controller.cpp
  first_bullet_controller.cpp
  flare.cpp
  Flashlight.cpp
  FoodItem.cpp
  FoodItem_script.cpp
  FryupZone.cpp
  fs_registrator_script.cpp
  GalantineArtifact.cpp
  GameObject.cpp
  GamePersistent.cpp
  gamespy/cdkeydecode/base32.c
  gamespy/cdkeydecode/cdkeydecode.c
  GameTask.cpp
  GametaskManager.cpp
  GameTask_script.cpp
  game_base.cpp
  game_cl_artefacthunt.cpp
  game_cl_base.cpp
  game_cl_base_weapon_usage_statistic.cpp
  game_cl_base_weapon_usage_statistic_save.cpp
  game_cl_capturetheartefact_buywnd.cpp
  game_cl_capture_the_artefact.cpp
  game_cl_capture_the_artefact_captions_manager.cpp
  game_cl_capture_the_artefact_messages_menu.cpp
  game_cl_deathmatch.cpp
  game_cl_deathmatch_buywnd.cpp
  game_cl_mp.cpp
  game_cl_mp_messages_menu.cpp
  game_cl_mp_snd_messages.cpp
  game_cl_single.cpp
  game_cl_teamdeathmatch.cpp
  game_graph_script.cpp
  game_news.cpp
  game_state_accumulator.cpp
  game_state_accumulator_state_register.cpp
  game_sv_artefacthunt.cpp
  game_sv_artefacthunt_process_event.cpp
  game_sv_base.cpp
  game_sv_base_console_vars.cpp
  game_sv_capture_the_artefact.cpp
  game_sv_capture_the_artefact_buy_event.cpp
  game_sv_capture_the_artefact_myteam_impl.cpp
  game_sv_capture_the_artefact_process_event.cpp
  game_sv_deathmatch.cpp
  game_sv_deathmatch_process_event.cpp
  game_sv_event_queue.cpp
  game_sv_item_respawner.cpp
  game_sv_mp.cpp
  game_sv_single.cpp
  game_sv_teamdeathmatch.cpp
  game_sv_teamdeathmatch_process_event.cpp
  GlobalFeelTouch.cpp
  GraviArtifact.cpp
  GraviZone.cpp
  Grenade.cpp
  GrenadeLauncher.cpp
  group_hierarchy_holder.cpp
  gsc_dsigned_ltx.cpp
  HairsZone.cpp
  HairsZone_script.cpp
  HangingLamp.cpp
  harvest_time.cpp
  Helicopter.cpp
  Helicopter2.cpp
  HelicopterMovementManager.cpp
  HelicopterWeapon.cpp
  helicopter_script.cpp
  Hit.cpp
  HitMarker.cpp
  hits_store.cpp
  hit_immunity.cpp
  holder_custom.cpp
  holder_custom_script.cpp
  HUDCrosshair.cpp
  HudItem.cpp
  HUDManager.cpp
  HUDRecon.cpp
  HudSound.cpp
  HUDTarget.cpp
  hud_item_object.cpp
  IKFoot.cpp
  IKLimbscontroller.cpp
  ik/aint.cxx
  ik/Dof7control.cpp
  ik/eqn.cxx
  ik/eulersolver.cxx
  ik/IKLimb.cpp
  ik/jtlimits.cxx
  ik/limb.cxx
  ik/math3d.cpp
  ik/mathTrig.cpp
  ik_anim_state.cpp
  ik_calculate_data.cpp
  ik_dbg_matrix.cpp
  ik_foot_collider.cpp
  ik_limb_state.cpp
  ik_object_shift.cpp
  imotion_position.cpp
  imotion_velocity.cpp
  InfoDocument.cpp
  InfoPortion.cpp
  interactive_animation.cpp
  interactive_motion.cpp
  Inventory.cpp
  InventoryBox.cpp
  InventoryBox_script.cpp
  InventoryOwner.cpp
  InventoryOwner_script.cpp
  inventory_item.cpp
  inventory_item_object.cpp
  inventory_item_script.cpp
  inventory_item_upgrade.cpp
  inventory_owner_info.cpp
  inventory_quickswitch.cpp
  inventory_upgrade.cpp
  inventory_upgrade_base.cpp
  inventory_upgrade_group.cpp
  inventory_upgrade_manager.cpp
  inventory_upgrade_property.cpp
  inventory_upgrade_root.cpp
  invincible_fury.cpp
  key_binding_registrator_script.cpp
  killer_victim_velocity_angle.cpp
  kills_store.cpp
  Level.cpp
  LevelDebugScript.cpp
  Level_Bullet_Manager.cpp
  Level_bullet_manager_firetrace.cpp
  level_changer.cpp
  level_debug.cpp
  Level_GameSpy_Funcs.cpp
  level_graph.cpp
  level_graph_debug.cpp
  level_graph_debug2.cpp
  level_graph_vertex.cpp
  Level_input.cpp
  Level_load.cpp
  level_map_locations.cpp
  Level_network.cpp
  Level_network_compressed_updates.cpp
  Level_network_Demo.cpp
  Level_network_digest_computer.cpp
  Level_network_map_sync.cpp
  Level_network_messages.cpp
  Level_network_spawn.cpp
  Level_network_start_client.cpp
  level_script.cpp
  Level_secure_messaging.cpp
  Level_SLS_Default.cpp
  Level_SLS_Load.cpp
  Level_SLS_Save.cpp
  level_sounds.cpp
  Level_start.cpp
  login_manager.cpp
  login_manager_script.cpp
  magic_box3.cpp
  magic_minimize_1d.cpp
  MainMenu.cpp
  map_location.cpp
  map_manager.cpp
  map_spot.cpp
  medkit.cpp
  medkit_script.cpp
  MercuryBall.cpp
  Message_Filter.cpp
  MilitaryOutfit.cpp
  Mincer.cpp
  mincer_script.cpp
  min_obb.cpp
  Missile.cpp
  monster_community.cpp
  MosquitoBald.cpp
  MosquitoBald_script.cpp
  moving_bones_snd_player.cpp
  mpactor_dump_impl.cpp
  MPPlayersBag.cpp
  mp_config_sections.cpp
  Needles.cpp
  NoGravityZone.cpp
  obstacles_query.cpp
  ParticlesObject.cpp
  ParticlesPlayer.cpp
  particle_params.cpp
  particle_params_script.cpp
  patrol_path.cpp
  patrol_path_manager.cpp
  patrol_path_params.cpp
  patrol_path_params_script.cpp
  patrol_path_storage.cpp
  patrol_point.cpp
  PDA.cpp
  Phrase.cpp
  PhraseDialog.cpp
  PhraseDialogManager.cpp
  PhraseDialog_script.cpp
  PhraseScript.cpp
  player_account.cpp
  player_hud.cpp
  player_hud_script.cpp
  player_hud_tune.cpp
  player_name_modifyer.cpp
  player_spot_params.cpp
  player_state_achilles_heel.cpp
  player_state_ambassador.cpp
  player_state_ammo_elapsed.cpp
  player_state_avenger.cpp
  player_state_blitzkrieg.cpp
  player_state_cherub.cpp
  player_state_climber.cpp
  player_state_mad.cpp
  player_state_marksman.cpp
  player_state_multichampion.cpp
  player_state_opener.cpp
  player_state_params.cpp
  player_state_remembrance.cpp
  player_state_skewer.cpp
  player_state_toughy.cpp
  player_team_win_score.cpp
  poses_blending.cpp
  pose_extrapolation.cpp
  PostprocessAnimator.cpp
  pp_effector_custom.cpp
  pp_effector_distance.cpp
  profile_data_types.cpp
  profile_data_types_script.cpp
  profile_store.cpp
  profile_store_script.cpp
  purchase_list.cpp
  RadioactiveZone.cpp
  random32.cpp
  rat_states.cpp
  rat_state_base.cpp
  rat_state_manager.cpp
  raypick.cpp
  RegistryFuncs.cpp
  relation_registry.cpp
  relation_registry_actions.cpp
  relation_registry_fights.cpp
  restricted_object_obstacle.cpp
  rewarding_events_handlers.cpp
  rewarding_state_events.cpp
  reward_event_generator.cpp
  reward_manager.cpp
  RGD5.cpp
  RocketLauncher.cpp
  RustyHairArtifact.cpp
  saved_game_wrapper.cpp
  saved_game_wrapper_script.cpp
  ScientificOutfit.cpp
  Scope.cpp
  screenshots_common.cpp
  screenshots_writer.cpp
  screenshot_manager.cpp
  screenshot_server.cpp
  ScriptXMLInit.cpp
  searchlight.cpp
  secure_messaging.cpp
  seniority_hierarchy_holder.cpp
  server_entity_wrapper.cpp
  ShootingObject.cpp
  shootingObject_dump_impl.cpp
  Silencer.cpp
  silent_shots.cpp
  SimpleDetector.cpp
  space_restrictor.cpp
  space_restrictor_script.cpp
  Spectator.cpp
  spectator_camera_first_eye.cpp
  sprinter_stopper.cpp
  squad_hierarchy_holder.cpp
  stalkerOutfit.cpp
  stalker_alife_actions.cpp
  stalker_alife_planner.cpp
  stalker_alife_task_actions.cpp
  stalker_animation_callbacks.cpp
  stalker_animation_data.cpp
  stalker_animation_data_storage.cpp
  stalker_animation_global.cpp
  stalker_animation_head.cpp
  stalker_animation_legs.cpp
  stalker_animation_manager.cpp
  stalker_animation_manager_debug.cpp
  stalker_animation_manager_update.cpp
  stalker_animation_names.cpp
  stalker_animation_pair.cpp
  stalker_animation_script.cpp
  stalker_animation_state.cpp
  stalker_animation_torso.cpp
  stalker_anomaly_actions.cpp
  stalker_anomaly_planner.cpp
  stalker_base_action.cpp
  stalker_combat_actions.cpp
  stalker_combat_action_base.cpp
  stalker_combat_planner.cpp
  stalker_danger_by_sound_actions.cpp
  stalker_danger_by_sound_planner.cpp
  stalker_danger_grenade_actions.cpp
  stalker_danger_grenade_planner.cpp
  stalker_danger_in_direction_actions.cpp
  stalker_danger_in_direction_planner.cpp
  stalker_danger_planner.cpp
  stalker_danger_property_evaluators.cpp
  stalker_danger_unknown_actions.cpp
  stalker_danger_unknown_planner.cpp
  stalker_death_actions.cpp
  stalker_death_planner.cpp
  stalker_flair.cpp
  stalker_get_distance_actions.cpp
  stalker_get_distance_planner.cpp
  stalker_kill_wounded_actions.cpp
  stalker_kill_wounded_planner.cpp
  stalker_low_cover_actions.cpp
  stalker_low_cover_planner.cpp
  stalker_movement_manager_base.cpp
  stalker_movement_manager_obstacles.cpp
  stalker_movement_manager_obstacles_path.cpp
  stalker_movement_manager_smart_cover.cpp
  stalker_movement_manager_smart_cover_fov_range.cpp
  stalker_movement_manager_smart_cover_loopholes.cpp
  stalker_movement_params.cpp
  stalker_planner.cpp
  stalker_property_evaluators.cpp
  stalker_search_actions.cpp
  stalker_search_planner.cpp
  stalker_sound_data.cpp
  stalker_sound_data_visitor.cpp
  stalker_velocity_collection.cpp
  stalker_velocity_holder.cpp
  state_arguments_functions.cpp
  #static_cast_checked_test.cpp
  static_obstacles_avoider.cpp
  stats_submitter.cpp
  stats_submitter_dsa_params.cpp
  steering_behaviour.cpp
  string_table.cpp
  team_base_zone.cpp
  team_hierarchy_holder.cpp
  TeleWhirlwind.cpp
  ThornArtifact.cpp
  Torch.cpp
  torch_script.cpp
  TorridZone.cpp
  Tracer.cpp
  trade.cpp
  trade2.cpp
  trade_parameters.cpp
  traffic_optimization.cpp
  trajectories.cpp
  UsableScriptObject.cpp
  wallmark_manager.cpp
  Weapon.cpp
  WeaponAK74.cpp
  WeaponAmmo.cpp
  WeaponAmmo_script.cpp
  WeaponAutomaticShotgun.cpp
  WeaponBinoculars.cpp
  WeaponBinocularsVision.cpp
  WeaponBinoculars_script.cpp
  weaponBM16.cpp
  weaponBM16_script.cpp
  WeaponCustomAuto.cpp
  WeaponCustomPistol.cpp
  WeaponDispersion.cpp
  WeaponFire.cpp
  WeaponFN2000.cpp
  WeaponFORT.cpp
  WeaponGroza.cpp
  WeaponHPSA.cpp
  WeaponHPSA_script.cpp
  WeaponKnife.cpp
  WeaponKnife_script.cpp
  WeaponLR300.cpp
  WeaponMagazined.cpp
  WeaponMagazinedWGrenade.cpp
  WeaponMagazineExtended.cpp
  WeaponPistol.cpp
  WeaponPM.cpp
  WeaponRevolver.cpp
  WeaponRG6.cpp
  WeaponRG6_script.cpp
  WeaponRPG7.cpp
  WeaponRPG7_script.cpp
  WeaponShotgun.cpp
  weaponshotgun_script.cpp
  WeaponSSRS.cpp
  WeaponSSRS_script.cpp
  WeaponStatMgun.cpp
  HolderEntityObject.cpp
  WeaponStatMgunFire.cpp
  WeaponStatMgunIR.cpp
  WeaponSVD.cpp
  WeaponSVU.cpp
  WeaponUpgrade.cpp
  WeaponUSP45.cpp
  WeaponVal.cpp
  WeaponVintorez.cpp
  WeaponWalther.cpp
  weapon_ammo_dump_impl.cpp
  weapon_dump_impl.cpp
  Wound.cpp
  xrClientsPool.cpp
  xrGame.cpp
  xrGameSpyServer.cpp
  xrGameSpyServer_callbacks.cpp
  xrGameSpy_GameSpyFuncs.cpp
  xrgame_dll_detach.cpp
  xrServer.cpp
  xrServerMapSync.cpp
  xrServer_balance.cpp
  xrServer_CL_connect.cpp
  xrServer_CL_disconnect.cpp
  xrServer_Connect.cpp
  xrServer_Disconnect.cpp
  xrServer_info.cpp
  xrServer_perform_GameExport.cpp
  xrServer_perform_migration.cpp
  xrServer_perform_RPgen.cpp
  xrServer_perform_sls_default.cpp
  xrServer_perform_sls_load.cpp
  xrServer_perform_sls_save.cpp
  xrServer_perform_transfer.cpp
  xrServer_process_event.cpp
  xrServer_process_event_activate.cpp
  xrServer_process_event_destroy.cpp
  xrServer_process_event_ownership.cpp
  xrServer_process_event_reject.cpp
  xrServer_process_spawn.cpp
  xrServer_process_update.cpp
  xrServer_secure_messaging.cpp
  xrServer_sls_clear.cpp
  xrServer_svclient_validation.cpp
  xrServer_updates_compressor.cpp
  xr_dsa_signer.cpp
  xr_dsa_verifyer.cpp
  xr_level_controller.cpp
  xr_time.cpp
  ZoneCampfire.cpp
  ZoneVisual.cpp
  zone_effector.cpp
  ZudaArtifact.cpp

  ../xrCore/ChooseTypes.H
  ../xrServerEntities/ai_sounds.h
  ../xrServerEntities/alife_human_brain.h
  ../xrServerEntities/alife_human_brain_inline.h
  ../xrServerEntities/alife_monster_brain.h
  ../xrServerEntities/alife_monster_brain_inline.h
  ../xrServerEntities/alife_movement_manager_holder.h
  ../xrServerEntities/alife_space.h
  ../xrServerEntities/associative_vector.h
  ../xrServerEntities/associative_vector_compare_predicate.h
  ../xrServerEntities/associative_vector_compare_predicate_inline.h
  ../xrServerEntities/associative_vector_inline.h
  ../xrServerEntities/character_info.h
  ../xrServerEntities/character_info_defs.h
  ../xrServerEntities/clsid_game.h
  ../xrCore/FastDelegate.h
  ../xrServerEntities/gametype_chooser.h
  ../xrServerEntities/game_base_space.h
  ../xrServerEntities/game_graph_space.h
  ../xrServerEntities/InfoPortionDefs.h
  ../xrServerEntities/inventory_space.h
  ../xrServerEntities/ItemListTypes.h
  ../xrServerEntities/LevelGameDef.h
  ../xrServerEntities/lua_studio.h
  ../xrServerEntities/mslotutils.h
  ../xrServerEntities/object_broker.h
  ../xrServerEntities/object_cloner.h
  ../xrServerEntities/object_comparer.h
  ../xrServerEntities/object_destroyer.h
  ../xrServerEntities/object_factory.h
  ../xrServerEntities/object_factory_impl.h
  ../xrServerEntities/object_factory_inline.h
  ../xrServerEntities/object_factory_space.h
  ../xrServerEntities/object_interfaces.h
  ../xrServerEntities/object_item_abstract.h
  ../xrServerEntities/object_item_abstract_inline.h
  ../xrServerEntities/object_item_client_server.h
  ../xrServerEntities/object_item_client_server_inline.h
  ../xrServerEntities/object_item_script.h
  ../xrServerEntities/object_item_single.h
  ../xrServerEntities/object_item_single_inline.h
  ../xrServerEntities/object_loader.h
  ../xrServerEntities/object_saver.h
  ../xrServerEntities/object_type_traits.h
  ../xrServerEntities/pch_script.h
  ../xrServerEntities/PropertiesListTypes.h
  ../xrServerEntities/script_callStack.h
  ../xrServerEntities/script_debugger.h
  ../xrServerEntities/script_debugger_messages.h
  ../xrServerEntities/script_debugger_threads.h
  ../xrServerEntities/script_engine.h
  ../xrServerEntities/script_engine_export.h
  ../xrServerEntities/script_engine_inline.h
  ../xrServerEntities/script_engine_space.h
  ../xrServerEntities/script_export_macroses.h
  ../xrServerEntities/script_export_space.h
  ../xrServerEntities/script_fcolor.h
  ../xrServerEntities/script_flags.h
  ../xrServerEntities/script_fmatrix.h
  ../xrServerEntities/script_fvector.h
  ../xrServerEntities/script_ini_file.h
  ../xrServerEntities/script_ini_file_inline.h
  ../xrServerEntities/script_lua_helper.h
  ../xrServerEntities/script_net_packet.h
  ../xrServerEntities/script_process.h
  ../xrServerEntities/script_process_inline.h
  ../xrServerEntities/script_reader.h
  ../xrServerEntities/script_rtoken_list.h
  ../xrServerEntities/script_rtoken_list_inline.h
  ../xrServerEntities/script_sound_type.h
  ../xrServerEntities/script_space_forward.h
  ../xrServerEntities/script_stack_tracker.h
  ../xrServerEntities/script_stack_tracker_inline.h
  ../xrServerEntities/script_storage.h
  ../xrServerEntities/script_storage_inline.h
  ../xrServerEntities/script_storage_space.h
  ../xrServerEntities/script_thread.h
  ../xrServerEntities/script_thread_inline.h
  ../xrServerEntities/script_token_list.h
  ../xrServerEntities/script_token_list_inline.h
  ../xrServerEntities/script_value_container.h
  ../xrServerEntities/script_value_container_impl.h
  ../xrServerEntities/ShapeData.h
  ../xrServerEntities/shared_data.h
  ../xrServerEntities/smart_cast.h
  ../xrServerEntities/smart_cast_impl0.h
  ../xrServerEntities/smart_cast_impl1.h
  ../xrServerEntities/smart_cast_impl2.h
  ../xrServerEntities/specific_character.h
  ../xrServerEntities/WaveForm.h
  ../xrServerEntities/xml_str_id_loader.h
  ../xrServerEntities/xrEProps.h
  ../xrServerEntities/xrMessages.h
  ../xrServerEntities/xrServer_Objects.h
  ../xrServerEntities/xrServer_Objects_Abstract.h
  ../xrServerEntities/xrServer_Objects_ALife.h
  ../xrServerEntities/xrServer_Objects_ALife_All.h
  ../xrServerEntities/xrServer_Objects_ALife_Items.h
  ../xrServerEntities/xrServer_Objects_ALife_monsters.h
  ../xrServerEntities/xrServer_Objects_Alife_Smartcovers.h
  ../xrServerEntities/xrServer_Object_Base.h
  ../xrServerEntities/xrServer_script_macroses.h
  ../xrServerEntities/xrServer_Space.h
  account_manager.h
  account_manager_console.h
  accumulative_states.h
  action_base.h
  action_base_inline.h
  action_management_config.h
  ActivatingCharCollisionDelay.h
  Actor.h
  ActorAnimation.h
  ActorBackpack.h
  ActorCondition.h
  ActorEffector.h
  ActorHelmet.h
  ActorNightVision.h
  actor_anim_defs.h
  actor_defs.h
  Actor_Flags.h
  actor_input_handler.h
  actor_memory.h
  actor_mp_client.h
  actor_mp_server.h
  actor_mp_state.h
  actor_mp_state_inline.h
  actor_statistic_defs.h
  actor_statistic_mgr.h
  AdvancedDetector.h
  agent_corpse_manager.h
  agent_corpse_manager_inline.h
  agent_enemy_manager.h
  agent_enemy_manager_inline.h
  agent_explosive_manager.h
  agent_explosive_manager_inline.h
  agent_location_manager.h
  agent_location_manager_inline.h
  agent_manager.h
  agent_manager_actions.h
  agent_manager_inline.h
  agent_manager_planner.h
  agent_manager_properties.h
  agent_manager_properties_inline.h
  agent_manager_space.h
  agent_member_manager.h
  agent_member_manager_inline.h
  agent_memory_manager.h
  agent_memory_manager_inline.h
  alife_abstract_registry.h
  alife_abstract_registry_inline.h
  alife_combat_manager.h
  alife_combat_manager_inline.h
  alife_communication_manager.h
  alife_communication_manager_inline.h
  alife_communication_space.h
  alife_graph_registry.h
  alife_graph_registry_inline.h
  alife_group_registry.h
  alife_group_registry_inline.h
  alife_human_brain_save.h
  alife_human_object_handler.h
  alife_human_object_handler_inline.h
  alife_human_object_handler_save.h
  alife_interaction_manager.h
  alife_interaction_manager_inline.h
  alife_level_registry.h
  alife_level_registry_inline.h
  alife_monster_detail_path_manager.h
  alife_monster_detail_path_manager_inline.h
  alife_monster_movement_manager.h
  alife_monster_movement_manager_inline.h
  alife_monster_patrol_path_manager.h
  alife_monster_patrol_path_manager_inline.h
  alife_object_registry.h
  alife_object_registry_inline.h
  alife_online_offline_group_brain.h
  alife_online_offline_group_brain_inline.h
  alife_registry_container.h
  alife_registry_container_composition.h
  alife_registry_container_inline.h
  alife_registry_container_space.h
  alife_registry_wrapper.h
  alife_registry_wrappers.h
  alife_schedule_registry.h
  alife_schedule_registry_inline.h
  alife_simulator.h
  alife_simulator_base.h
  alife_simulator_base_inline.h
  alife_simulator_header.h
  alife_simulator_header_inline.h
  alife_simulator_inline.h
  alife_smart_terrain_registry.h
  alife_smart_terrain_registry_inline.h
  alife_smart_terrain_task.h
  alife_smart_terrain_task_inline.h
  alife_spawn_registry.h
  alife_spawn_registry_header.h
  alife_spawn_registry_header_inline.h
  alife_spawn_registry_inline.h
  alife_storage_manager.h
  alife_storage_manager_inline.h
  alife_story_registry.h
  alife_story_registry_inline.h
  alife_surge_manager.h
  alife_surge_manager_inline.h
  alife_switch_manager.h
  alife_switch_manager_inline.h
  alife_time_manager.h
  alife_time_manager_inline.h
  alife_update_manager.h
  alife_update_manager_inline.h
  AmebaZone.h
  ammunition_groups.h
  animation_movement_controller.h
  animation_script_callback.h
  animation_utils.h
  anticheat_dumpable_object.h
  antirad.h
  Artefact.h
  artefact_activation.h
  atlas_stalkercoppc_v1.h
  atlas_submit_queue.h
  attachable_item.h
  attachable_item_inline.h
  attachment_owner.h
  attachment_owner_inline.h
  autosave_manager.h
  autosave_manager_inline.h
  awards_store.h
  a_star.h
  a_star_inline.h
  base_client_classes.h
  base_client_classes_wrappers.h
  BastArtifact.h
  best_scores_helper.h
  best_scores_store.h
  BlackDrops.h
  BlackGraviArtifact.h
  black_list.h
  Bolt.h
  BoneProtections.h
  bone_groups.h
  BottleItem.h
  BreakableObject.h
  builder_allocator_constructor.h
  builder_allocator_constructor_inline.h
  callback_info.h
  CameraEffector.h
  CameraFirstEye.h
  cameralook.h
  CameraRecoil.h
  CaptureBoneCallback.h
  Car.h
  CarDamageParticles.h
  CarLights.h
  CarWeapon.h
  car_memory.h
  cdkey_ban_list.h
  CharacterPhysicsSupport.h
  character_community.h
  character_hit_animations.h
  character_hit_animations_params.h
  character_rank.h
  character_reputation.h
  character_shell_control.h
  client_spawn_manager.h
  client_spawn_manager_inline.h
  ClimableObject.h
  command_switch_counter.h
  configs_common.h
  configs_dumper.h
  configs_dump_verifyer.h
  console_registrator.h
  controller_state_panic_inline.h
  cover_evaluators.h
  cover_evaluators_inline.h
  cta_game_artefact.h
  cta_game_artefact_activation.h
  CustomDetector.h
  CustomDevice.h
  CustomMonster.h
  CustomMonster_inline.h
  CustomOutfit.h
  CustomRocket.h
  CustomZone.h
  DamagableItem.h
  danger_cover_location.h
  danger_cover_location_inline.h
  danger_explosive.h
  danger_explosive_inline.h
  danger_location.h
  danger_location_inline.h
  danger_object_location.h
  danger_object_location_inline.h
  data_storage_binary_heap.h
  data_storage_binary_heap_inline.h
  data_storage_bucket_list.h
  data_storage_bucket_list_inline.h
  data_storage_constructor.h
  data_storage_double_linked_list.h
  data_storage_double_linked_list_inline.h
  data_storage_single_linked_list.h
  data_storage_single_linked_list_inline.h
  date_time.h
  death_anims.h
  debug_make_final.hpp
  debug_renderer.h
  debug_renderer_inline.h
  debug_text_tree.h
  debug_text_tree_inline.h
  DelayedActionFuse.h
  DemoInfo.h
  DemoInfo_Loader.h
  DemoPlay_Control.h
  DestroyablePhysicsObject.h
  dijkstra.h
  dijkstra_inline.h
  doors.h
  Dosimeter.h
  double_shot_double_kill.h
  DummyArtifact.h
  DynamicHeightMap.h
  dynamic_obstacles_avoider.h
  dynamic_obstacles_avoider_inline.h
  eatable_item.h
  eatable_item_object.h
  edge_path.h
  edge_path_inline.h
  EffectorBobbing.h
  EffectorFall.h
  EffectorShot.h
  EffectorShotX.h
  EffectorZoomInertion.h
  ef_base.h
  ef_pattern.h
  ef_primary.h
  ef_storage.h
  ef_storage_inline.h
  ElectricBall.h
  EliteDetector.h
  encyclopedia_article.h
  encyclopedia_article_defs.h
  Entity.h
  EntityCondition.h
  entity_alive.h
  entity_alive_inline.h
  event_conditions_collection.h
  ExoOutfit.h
  #Explosive.h
  ExplosiveItem.h
  ExplosiveRocket.h
  F1.h
  FadedBall.h
  faster_than_bullets_time.h
  filereceiver_node.h
  filetransfer_common.h
  filetransfer_node.h
  file_transfer.h
  firedeps.h
  fire_disp_controller.h
  first_bullet_controller.h
  flare.h
  Flashlight.h
  FoodItem.h
  FryupZone.h
  fs_registrator.h
  GalantineArtifact.h
  GameObject.h
  GamePersistent.h
  gamespy/cdkeydecode/base32.h
  gamespy/cdkeydecode/cdkeydecode.h
  GameTask.h
  GameTaskDefs.h
  GametaskManager.h
  game_base.h
  game_base_kill_type.h
  game_base_menu_events.h
  game_cl_artefacthunt.h
  game_cl_artefacthunt_snd_msg.h
  game_cl_base.h
  game_cl_base_weapon_usage_statistic.h
  game_cl_capturetheartefact_snd_msg.h
  game_cl_capture_the_artefact.h
  game_cl_capture_the_artefact_captions_manager.h
  game_cl_deathmatch.h
  game_cl_deathmatch_snd_messages.h
  game_cl_mp.h
  game_cl_mp_messages_menu.h
  game_cl_mp_snd_messages.h
  game_cl_single.h
  game_cl_teamdeathmatch.h
  game_cl_teamdeathmatch_snd_messages.h
  game_events_handler.h
  game_graph.h
  game_graph_inline.h
  game_level_cross_table.h
  game_level_cross_table_inline.h
  game_news.h
  game_object_space.h
  game_state_accumulator.h
  game_state_accumulator_inline.h
  game_sv_artefacthunt.h
  game_sv_base.h
  game_sv_base_console_vars.h
  game_sv_capture_the_artefact.h
  game_sv_deathmatch.h
  game_sv_event_queue.h
  game_sv_item_respawner.h
  game_sv_mp.h
  game_sv_mp_team.h
  game_sv_mp_vote_flags.h
  game_sv_single.h
  game_sv_teamdeathmatch.h
  GlobalFeelTouch.hpp
  graph_edge.h
  graph_edge_inline.h
  graph_engine.h
  graph_engine_inline.h
  graph_engine_space.h
  graph_vertex.h
  graph_vertex_inline.h
  GraviArtifact.h
  GraviZone.h
  Grenade.h
  GrenadeLauncher.h
  group_hierarchy_holder.h
  group_hierarchy_holder_inline.h
  gsc_dsigned_ltx.h
  HairsZone.h
  HangingLamp.h
  harvest_time.h
  helicopter.h
  Hit.h
  HitMarker.h
  hits_store.h
  hits_store_inline.h
  hit_immunity.h
  hit_immunity_space.h
  holder_custom.h
  HUDCrosshair.h
  HudItem.h
  HUDManager.h
  HUDRecon.h
  HudSound.h
  HUDTarget.h
  hud_item_object.h
  id_generator.h
  IKFoot.h
  IKFoot_inl.h
  IKLimbscontroller.h
  ik/aint.h
  ik/Dof7control.h
  ik/eqn.h
  ik/eulersolver.h
  ik/IKLimb.h
  ik/jtlimits.h
  ik/limb.h
  ik/math3d.h
  ik/mathTrig.h
  ik_anim_state.h
  ik_calculate_data.h
  ik_calculate_state.h
  ik_collide_data.h
  ik_dbg_matrix.h
  ik_foot_collider.h
  ik_limb_state.h
  ik_limb_state_predict.h
  ik_object_shift.h
  imotion_position.h
  imotion_velocity.h
  InfoDocument.h
  InfoPortion.h
  ini_id_loader.h
  ini_table_loader.h
  interactive_animation.h
  interactive_motion.h
  Inventory.h
  InventoryBox.h
  InventoryOwner.h
  inventory_item.h
  inventory_item_impl.h
  inventory_item_inline.h
  inventory_item_object.h
  inventory_item_object_inline.h
  inventory_owner_inline.h
  inventory_upgrade.h
  inventory_upgrade_base.h
  inventory_upgrade_base_inline.h
  inventory_upgrade_group.h
  inventory_upgrade_group_inline.h
  inventory_upgrade_inline.h
  inventory_upgrade_manager.h
  inventory_upgrade_manager_inline.h
  inventory_upgrade_property.h
  inventory_upgrade_property_inline.h
  inventory_upgrade_root.h
  inventory_upgrade_root_inline.h
  invincible_fury.h
  key_binding_registrator.h
  killer_victim_velocity_angle.h
  kills_store.h
  kills_store_inline.h
  Level.h
  LevelDebugScript.h
  Level_Bullet_Manager.h
  level_changer.h
  level_debug.h
  level_graph.h
  level_graph_inline.h
  level_graph_space.h
  level_graph_vertex_inline.h
  level_location_selector.h
  level_location_selector_inline.h
  Level_network_Demo.h
  Level_network_map_sync.h
  level_sounds.h
  login_manager.h
  magic_box3.h
  magic_box3_inline.h
  magic_minimize_1d.h
  magic_minimize_1d_inline.h
  magic_minimize_nd.h
  magic_minimize_nd_inline.h
  MainMenu.h
  manager_builder_allocator_constructor.h
  manager_builder_allocator_constructor_inline.h
  map_location.h
  map_location_defs.h
  map_manager.h
  map_spot.h
  medkit.h
  member_corpse.h
  member_corpse_inline.h
  member_enemy.h
  member_enemy_inline.h
  member_order.h
  member_order_inline.h
  MercuryBall.h
  Message_Filter.h
  MilitaryOutfit.h
  Mincer.h
  Missile.h
  mixed_delegate.h
  mixed_delegate_unique_tags.h
  monster_community.h
  MosquitoBald.h
  moving_bones_snd_player.h
  MPPlayersBag.h
  mp_config_sections.h
  mt_config.h
  Needles.h
  NET_Queue.h
  NewZoomFlag.h
  new_sds.h
  NoGravityZone.h
  object_manager.h
  object_manager_inline.h
  obsolete_queue.h
  obsolete_queue_inline.h
  obstacles_query.h
  obstacles_query_inline.h
  ParticlesObject.h
  ParticlesPlayer.h
  particle_params.h
  particle_params_inline.h
  path_manager.h
  path_manager_game.h
  path_manager_game_inline.h
  path_manager_game_level.h
  path_manager_game_level_inline.h
  path_manager_game_vertex.h
  path_manager_game_vertex_inline.h
  path_manager_generic.h
  path_manager_generic_inline.h
  path_manager_level.h
  path_manager_level_flooder.h
  path_manager_level_flooder_inline.h
  path_manager_level_inline.h
  path_manager_level_nearest_vertex.h
  path_manager_level_nearest_vertex_inline.h
  path_manager_level_straight_line.h
  path_manager_level_straight_line_inline.h
  path_manager_params.h
  path_manager_params_flooder.h
  path_manager_params_game_level.h
  path_manager_params_game_vertex.h
  path_manager_params_nearest_vertex.h
  path_manager_params_straight_line.h
  path_manager_solver.h
  path_manager_solver_inline.h
  patrol_path.h
  patrol_path_inline.h
  patrol_path_params.h
  patrol_path_params_inline.h
  patrol_path_storage.h
  patrol_path_storage_inline.h
  patrol_point.h
  patrol_point_inline.h
  PDA.h
  PdaMsg.h
  pda_space.h
  Phrase.h
  PhraseDialog.h
  PhraseDialogDefs.h
  PhraseDialogManager.h
  PhraseDialog_script.h
  PhraseScript.h
  PhysicObject.h
  PhysicsGamePars.h
  PhysicsShellHolder.h
  PhysicsSkeletonObject.h
  physics_element_scripted.h
  physics_game.h
  physics_joint_scripted.h
  physics_shell_animated.h
  physics_shell_scripted.h
  physics_world_scripted.h
  physic_item.h
  physic_item_inline.h
  ph_shell_interface.h
  player_account.h
  player_hud.h
  player_name_modifyer.h
  player_spot_params.h
  player_state_achilles_heel.h
  player_state_ambassador.h
  player_state_ammo_elapsed.h
  player_state_avenger.h
  player_state_blitzkrieg.h
  player_state_cherub.h
  player_state_climber.h
  player_state_mad.h
  player_state_marksman.h
  player_state_multichampion.h
  player_state_opener.h
  player_state_param.h
  player_state_params.h
  player_state_remembrance.h
  player_state_skewer.h
  player_state_toughy.h
  player_team_win_score.h
  poses_blending.h
  pose_extrapolation.h
  PostprocessAnimator.h
  pp_effector_custom.h
  pp_effector_distance.h
  profile_data_types.h
  profile_store.h
  purchase_list.h
  purchase_list_inline.h
  quadtree.h
  quadtree_inline.h
  queued_async_method.h
  RadioactiveZone.h
  random32.h
  rat_states.h
  rat_state_base.h
  rat_state_base_inline.h
  rat_state_manager.h
  rat_state_manager_inline.h
  raypick.h
  refreshable_obstacles_query.h
  refreshable_obstacles_query_inline.h
  RegistryFuncs.h
  relation_registry.h
  relation_registry_defs.h
  relation_registry_inline.h
  restricted_object_obstacle.h
  rewarding_events_handlers.h
  rewarding_state_events.h
  reward_event_generator.h
  reward_event_handler.h
  reward_manager.h
  reward_snd_messages.h
  RGD5.h
  RocketLauncher.h
  RustyHairArtifact.h
  safe_map_iterator.h
  safe_map_iterator_inline.h
  saved_game_wrapper.h
  saved_game_wrapper_inline.h
  ScientificOutfit.h
  Scope.h
  screenshots_common.h
  screenshots_writer.h
  screenshot_manager.h
  screenshot_server.h
  searchlight.h
  secure_messaging.h
  seniority_hierarchy_holder.h
  seniority_hierarchy_holder_inline.h
  seniority_hierarchy_space.h
  server_entity_wrapper.h
  server_entity_wrapper_inline.h
  ShootingObject.h
  Silencer.h
  silent_shots.h
  SimpleDetector.h
  smart_zone.h
  space_restrictor.h
  space_restrictor_inline.h
  Spectator.h
  spectator_camera_first_eye.h
  sprinter_stopper.h
  squad_hierarchy_holder.h
  squad_hierarchy_holder_inline.h
  stalkerOutfit.h
  stalker_alife_actions.h
  stalker_alife_planner.h
  stalker_alife_task_actions.h
  stalker_animation_data.h
  stalker_animation_data_storage.h
  stalker_animation_data_storage_inline.h
  stalker_animation_manager.h
  stalker_animation_manager_impl.h
  stalker_animation_manager_inline.h
  stalker_animation_names.h
  stalker_animation_pair.h
  stalker_animation_pair_inline.h
  stalker_animation_script.h
  stalker_animation_script_inline.h
  stalker_animation_state.h
  stalker_animation_state_inline.h
  stalker_anomaly_actions.h
  stalker_anomaly_planner.h
  stalker_base_action.h
  stalker_combat_actions.h
  stalker_combat_action_base.h
  stalker_combat_planner.h
  stalker_danger_by_sound_actions.h
  stalker_danger_by_sound_planner.h
  stalker_danger_grenade_actions.h
  stalker_danger_grenade_planner.h
  stalker_danger_in_direction_actions.h
  stalker_danger_in_direction_planner.h
  stalker_danger_planner.h
  stalker_danger_planner_inline.h
  stalker_danger_property_evaluators.h
  stalker_danger_unknown_actions.h
  stalker_danger_unknown_planner.h
  stalker_death_actions.h
  stalker_death_planner.h
  stalker_decision_space.h
  stalker_flair.h
  stalker_get_distance_actions.h
  stalker_get_distance_planner.h
  stalker_kill_wounded_actions.h
  stalker_kill_wounded_planner.h
  stalker_low_cover_actions.h
  stalker_low_cover_planner.h
  stalker_movement_manager_base.h
  stalker_movement_manager_base_inline.h
  stalker_movement_manager_obstacles.h
  stalker_movement_manager_obstacles_inline.h
  stalker_movement_manager_smart_cover.h
  stalker_movement_manager_smart_cover_inline.h
  stalker_movement_manager_space.h
  stalker_movement_params.h
  stalker_movement_params_inline.h
  stalker_movement_restriction.h
  stalker_movement_restriction_inline.h
  stalker_planner.h
  stalker_planner_inline.h
  stalker_property_evaluators.h
  stalker_property_evaluators_inline.h
  stalker_search_actions.h
  stalker_search_planner.h
  stalker_sound_data.h
  stalker_sound_data_inline.h
  stalker_sound_data_visitor.h
  stalker_sound_data_visitor_inline.h
  stalker_velocity_collection.h
  stalker_velocity_collection_inline.h
  stalker_velocity_holder.h
  stalker_velocity_holder_inline.h
  state_arguments_functions.h
  static_cast_checked.hpp
  static_obstacles_avoider.h
  static_obstacles_avoider_inline.h
  stats_submitter.h
  StdAfx.h
  steering_behaviour.h
  steering_behaviour_alignment.h
  steering_behaviour_base.h
  steering_behaviour_base_inline.h
  steering_behaviour_cohesion.h
  steering_behaviour_manager.h
  steering_behaviour_separation.h
  string_table.h
  string_table_defs.h
  team_base_zone.h
  team_hierarchy_holder.h
  team_hierarchy_holder_inline.h
  TeleWhirlwind.h
  ThornArtifact.h
  Torch.h
  TorridZone.h
  Tracer.h
  trade.h
  trade_action_parameters.h
  trade_action_parameters_inline.h
  trade_bool_parameters.h
  trade_bool_parameters_inline.h
  trade_factors.h
  trade_factors_inline.h
  trade_factor_parameters.h
  trade_factor_parameters_inline.h
  trade_parameters.h
  trade_parameters_inline.h
  traffic_optimization.h
  trajectories.h
  UsableScriptObject.h
  vertex_allocator_fixed.h
  vertex_allocator_fixed_inline.h
  vertex_manager_fixed.h
  vertex_manager_fixed_inline.h
  vertex_manager_hash_fixed.h
  vertex_manager_hash_fixed_inline.h
  vertex_path.h
  vertex_path_inline.h
  wallmark_manager.h
  Weapon.h
  WeaponAK74.h
  WeaponAmmo.h
  WeaponAutomaticShotgun.h
  WeaponBinoculars.h
  WeaponBinocularsVision.h
  weaponBM16.h
  WeaponCustomAuto.h
  WeaponCustomPistol.h
  WeaponFN2000.h
  WeaponFORT.h
  WeaponGroza.h
  WeaponHPSA.h
  WeaponKnife.h
  WeaponLR300.h
  WeaponMagazined.h
  WeaponMagazinedWGrenade.h
  WeaponPistol.h
  WeaponPM.h
  WeaponRevolver.h
  WeaponRG6.h
  WeaponRPG7.h
  WeaponShotgun.h
  WeaponSSRS.h
  WeaponStatMgun.h
  HolderEntityObject.h
  WeaponSVD.h
  WeaponSVU.h
  WeaponUSP45.h
  WeaponVal.h
  WeaponVintorez.h
  WeaponWalther.h
  Wound.h
  wrapper_abstract.h
  wrapper_abstract_inline.h
  xrClientsPool.h
  xrGameSpyServer.h
  xrGameSpyServer_callbacks.h
  xrServer.h
  xrServerMapSync.h
  xrServer_info.h
  xrServer_svclient_validation.h
  xrServer_updates_compressor.h
  xr_dsa_signer.h
  xr_dsa_verifyer.h
  xr_level_controller.h
  xr_time.h
  ZoneCampfire.h
  ZoneVisual.h
  zone_effector.h
  ZudaArtifact.h
)
