add_module(XRay.Game.Physics PRIVATE
  SOURCES
  ../xrServerEntities/PHNetState.cpp
  PHCollisionDamageReceiver.cpp
  PHCommander.cpp
  PHDebug.cpp
  PHDestroyable.cpp
  PHDestroyableNotificate.cpp
  PHMovementControl.cpp
  PHMovementDynamicActivate.cpp
  PHScriptCall.cpp
  PHShellCreator.cpp
  PHSimpleCalls.cpp
  PHSimpleCallsScript.cpp
  PHSkeleton.cpp
  PHSoundPlayer.cpp
  PhysicObject.cpp
  PhysicObject_script.cpp
  PhysicsGamePars.cpp
  PhysicsShellHolder.cpp
  PhysicsSkeletonObject.cpp
  physics_element_scripted.cpp
  physics_game.cpp
  physics_joint_scripted.cpp
  physics_shell_animated.cpp
  physics_shell_scripted.cpp
  physics_world_scripted.cpp
  physic_item.cpp
  
  ../xrServerEntities/PHNetState.h
  ../xrServerEntities/PHSynchronize.h
  PHCollisionDamageReceiver.h
  PHCommander.h
  PHDebug.h
  PHDestroyable.h
  PHDestroyableNotificate.h
  PHMovementControl.h
  PHReqComparer.h
  PHScriptCall.h
  PHShellCreator.h
  PHSimpleCalls.h
  PHSkeleton.h
  PHSoundPlayer.h
)
