inputs:
  toolchain:
    required: true
  target:
    required: true
  avx:
    required: true
  build-preset:
    required: true

env: 
  avx-segment: ${{inputs.avx && '.AVX' || ''}}

runs:
  using: composite
  steps:
      uses: actions/upload-artifact@v4.6.0
      env: 
        toolchain: ${{inputs.toolchain}}${{env.avx-segment}}
      with:
        name: ${{inputs.target}}${{env.avx-segment}}.PDB
        path: ./_build/${{env.toolchain}}/${{inputs.target}}.PDB.zip
        if-no-files-found: "error"
        retention-days: 1