inputs:
  toolchain:
    required: true
  targets:
    required: true
  avx:
    required: true
  build-preset:
    required: true

runs:
  using: composite
  steps:
    - uses: lukka/run-cmake@v10
      env:
        toolchain: ${{inputs.toolchain}}${{inputs.avx && '.AVX' || ''}}
        renderer: ${{inputs.renderer}}
        build-preset: ${{inputs.build-preset}}
        avx-segment: ${{inputs.avx && '.AVX' || ''}}
        build-target: Anomaly.${{inputs.renderer}}
      with:
        configurePreset: ${{env.toolchain}}
        buildPreset: "${{env.toolchain}}.${{env.build-preset}}"