include_guard()

# Normalize existing compiler flags
if(MSVC)
	string(REPLACE "/INCREMENTAL" "/INCREMENTAL:NO" CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO}")
endif()

# Append X-Ray linker flags
string(JOIN " " CMAKE_EXE_LINKER_FLAGS ${CMAKE_EXE_LINKER_FLAGS} ${XRAY_LINKER_FLAGS})
string(JOIN " " CMAKE_EXE_LINKER_FLAGS_DEBUG ${CMAKE_EXE_LINKER_FLAGS_DEBUG} ${XRAY_LINKER_FLAGS_DEBUG})
string(JOIN " " CMAKE_EXE_LINKER_FLAGS_RELEASE ${CMAKE_EXE_LINKER_FLAGS_RELEASE} ${XRAY_LINKER_FLAGS_RELEASE})
string(JOIN " " CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO ${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO} ${XRAY_LINKER_FLAGS_RELEASE})

# Setup Verified configuration
set(CMAKE_EXE_LINKER_FLAGS_VERIFIED "${CMAKE_EXE_LINKER_FLAGS_DEBUG}")

# Setup Profiled configuration
set(CMAKE_EXE_LINKER_FLAGS_PROFILED "${CMAKE_EXE_LINKER_FLAGS_RELEASE}")

# Print linker options
message("CMAKE_EXE_LINKER_FLAGS: ${CMAKE_EXE_LINKER_FLAGS}")
message("CMAKE_EXE_LINKER_FLAGS_DEBUG: ${CMAKE_EXE_LINKER_FLAGS_DEBUG}")
message("CMAKE_EXE_LINKER_FLAGS_VERIFIED: ${CMAKE_EXE_LINKER_FLAGS_VERIFIED}")
message("CMAKE_EXE_LINKER_FLAGS_PROFILED: ${CMAKE_EXE_LINKER_FLAGS_VERIFIED}")
message("CMAKE_EXE_LINKER_FLAGS_RELEASE: ${CMAKE_EXE_LINKER_FLAGS_RELEASE}")
message("CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO: ${CMAKE_EXE_LINKER_FLAGS_RELEASE}")