function(register_depend NAME PATH)
  set(DEPENDS_${NAME} ${PATH} PARENT_SCOPE)
endfunction()

register_depend(XRay.Render.API ${XRAY_SOURCES}/Layers/xrAPI)
register_depend(XRay.Render.Common ${XRAY_SOURCES}/Layers/xrRender)
register_depend(XRay.Collision ${XRAY_SOURCES}/xrCDB)
register_depend(XRay.Core ${XRAY_SOURCES}/xrCore)
register_depend(XRay.Core.Crypto ${XRAY_SOURCES}/xrCore/crypto)
register_depend(XRay.CPUPipe ${XRAY_SOURCES}/xrCPU_Pipe)
register_depend(XRay.Engine ${XRAY_SOURCES}/xrEngine)
register_depend(XRay.Game ${XRAY_SOURCES}/xrGame)
register_depend(XRay.NetServer ${XRAY_SOURCES}/xrNetServer)
register_depend(XRay.Particles ${XRAY_SOURCES}/xrParticles)
register_depend(XRay.Physics ${XRAY_SOURCES}/xrPhysics)
register_depend(XRay.ServerEntities ${XRAY_SOURCES}/xrServerEntities)
register_depend(XRay.Sound ${XRAY_SOURCES}/xrSound)
register_depend(XRay.XMLParser ${XRAY_SOURCES}/xrXMLParser)