inputs:
  toolchain:
    required: true
  target:
    required: true
  avx:
    required: true
  build-preset:
    required: true

env:
  toolchain: ${{inputs.toolchain}}
  target: ${{inputs.target}}
  build-preset: ${{inputs.build-preset}}
  avx-name: ${{inputs.avx && 'AVX' || ''}}
  avx-segment: ${{inputs.avx && '.AVX' || ''}}

runs:
  using: composite
  env: 
    toolchain: ${{env.toolchain}}${{env.avx-segment}}
  steps:
      run: cmake --build ./_build/${{env.toolchain}} --config ${{env.build-preset}} --target ${{env.target}}.PDB