add_library(crypto STATIC)

set_property(
  TARGET crypto
  PROPERTY FOLDER
  ${FOLDER_3RD_PARTY}
)

target_sources(crypto PRIVATE
  crypto.cpp
  xr_dsa.cpp
  xr_sha.cpp

  crypto.h
  crypto_api_def.h
)

target_sources_grouped(
  TARGET crypto
  NAME "OpenSSL/Source Files"
  FILES
  openssl/src/asn1_lib.c
  openssl/src/a_bitstr.c
  openssl/src/a_d2i_fp.c
  openssl/src/a_dup.c
  openssl/src/a_int.c
  openssl/src/a_object.c
  openssl/src/a_type.c
  openssl/src/bio_lib.c
  openssl/src/bn_add.c
  openssl/src/bn_asm.c
  openssl/src/bn_blind.c
  openssl/src/bn_ctx.c
  openssl/src/bn_div.c
  openssl/src/bn_exp.c
  openssl/src/bn_exp2.c
  openssl/src/bn_gcd.c
  openssl/src/bn_kron.c
  openssl/src/bn_lib.c
  openssl/src/bn_mod.c
  openssl/src/bn_mont.c
  openssl/src/bn_mul.c
  openssl/src/bn_prime.c
  openssl/src/bn_print.c
  openssl/src/bn_rand.c
  openssl/src/bn_recp.c
  openssl/src/bn_shift.c
  openssl/src/bn_sqr.c
  openssl/src/bn_sqrt.c
  openssl/src/bn_word.c
  openssl/src/bss_file.c
  openssl/src/buffer.c
  openssl/src/buf_str.c
  openssl/src/b_print.c
  openssl/src/cryptlib.c
  openssl/src/dh_check.c
  openssl/src/dh_key.c
  openssl/src/dh_lib.c
  openssl/src/digest.c
  openssl/src/dsa_asn1.c
  openssl/src/dsa_depr.c
  openssl/src/dsa_err.c
  openssl/src/dsa_gen.c
  openssl/src/dsa_key.c
  openssl/src/dsa_lib.c
  openssl/src/dsa_ossl.c
  openssl/src/dsa_sign.c
  openssl/src/dsa_utl.c
  openssl/src/dsa_vrf.c
  openssl/src/eng_ctrl.c
  openssl/src/eng_init.c
  openssl/src/eng_lib.c
  openssl/src/eng_list.c
  openssl/src/eng_table.c
  openssl/src/err.c
  openssl/src/err_def.c
  openssl/src/ex_data.c
  openssl/src/lhash.c
  openssl/src/md_rand.c
  openssl/src/mem.c
  openssl/src/mem_clr.c
  openssl/src/m_sha1.c
  openssl/src/obj_dat.c
  openssl/src/obj_lib.c
  openssl/src/rand_eng.c
  openssl/src/rand_lib.c
  openssl/src/rand_win.c
  openssl/src/rsa_lib.c
  openssl/src/rsa_sign.c
  openssl/src/sha1dgst.c
  openssl/src/sha1_one.c
  openssl/src/sha256.c
  openssl/src/sha512.c
  openssl/src/sha_dgst.c
  openssl/src/sha_one.c
  openssl/src/stack.c
  openssl/src/tasn_dec.c
  openssl/src/tasn_enc.c
  openssl/src/tasn_fre.c
  openssl/src/tasn_new.c
  openssl/src/tasn_typ.c
  openssl/src/tasn_utl.c
  openssl/src/tb_dh.c
  openssl/src/tb_digest.c
  openssl/src/tb_dsa.c
  openssl/src/tb_rand.c
  openssl/src/x_algor.c
  openssl/src/x_bignum.c
  openssl/src/x_long.c
  openssl/src/x_sig.c
)

target_sources_grouped(
  TARGET crypto
  NAME "OpenSSL/Header Files"
  FILES
  openssl/openssl/aes.h
  openssl/openssl/asn1.h
  openssl/openssl/asn1t.h
  openssl/openssl/asn1_mac.h
  openssl/openssl/bio.h
  openssl/openssl/blowfish.h
  openssl/openssl/bn.h
  openssl/openssl/buffer.h
  openssl/openssl/cast.h
  openssl/openssl/comp.h
  openssl/openssl/conf.h
  openssl/openssl/conf_api.h
  openssl/openssl/crypto.h
  openssl/openssl/des.h
  openssl/openssl/des_old.h
  openssl/openssl/dh.h
  openssl/openssl/dsa.h
  openssl/openssl/dso.h
  openssl/openssl/dtls1.h
  openssl/openssl/ebcdic.h
  openssl/openssl/ec.h
  openssl/openssl/ecdh.h
  openssl/openssl/ecdsa.h
  openssl/openssl/engine.h
  openssl/openssl/err.h
  openssl/openssl/evp.h
  openssl/openssl/e_os2.h
  openssl/openssl/hmac.h
  openssl/openssl/idea.h
  openssl/openssl/krb5_asn.h
  openssl/openssl/kssl.h
  openssl/openssl/lhash.h
  openssl/openssl/md2.h
  openssl/openssl/md4.h
  openssl/openssl/md5.h
  openssl/openssl/objects.h
  openssl/openssl/obj_mac.h
  openssl/openssl/ocsp.h
  openssl/openssl/opensslconf.h
  openssl/openssl/opensslv.h
  openssl/openssl/ossl_typ.h
  openssl/openssl/pem.h
  openssl/openssl/pem2.h
  openssl/openssl/pkcs12.h
  openssl/openssl/pkcs7.h
  openssl/openssl/pqueue.h
  openssl/openssl/pq_compat.h
  openssl/openssl/rand.h
  openssl/openssl/rc2.h
  openssl/openssl/rc4.h
  openssl/openssl/ripemd.h
  openssl/openssl/rsa.h
  openssl/openssl/safestack.h
  openssl/openssl/sha.h
  openssl/openssl/ssl.h
  openssl/openssl/ssl2.h
  openssl/openssl/ssl23.h
  openssl/openssl/ssl3.h
  openssl/openssl/stack.h
  openssl/openssl/store.h
  openssl/openssl/symhacks.h
  openssl/openssl/tls1.h
  openssl/openssl/tmdiff.h
  openssl/openssl/txt_db.h
  openssl/openssl/ui.h
  openssl/openssl/ui_compat.h
  openssl/openssl/x509.h
  openssl/openssl/x509v3.h
  openssl/openssl/x509_vfy.h
  openssl/src/bio_lcl.h
  openssl/src/bn_lcl.h
  openssl/src/bn_prime.h
  openssl/src/cryptlib.h
  openssl/src/eng_int.h
  openssl/src/evp_locl.h
  openssl/src/e_os.h
  openssl/src/md32_common.h
  openssl/src/obj_dat.h
  openssl/src/rand_lcl.h
  openssl/src/sha_locl.h
  xr_dsa.h
  xr_sha.h
)


target_include_directories(crypto
  PUBLIC
  ${CMAKE_CURRENT_SOURCE_DIR}
  PRIVATE
  ${CMAKE_CURRENT_SOURCE_DIR}/openssl
)

target_compile_definitions(crypto
  PRIVATE
  CRYPTO_BUILD
)
