name: Development

on:
  push:
    branches-ignore:
      - "cmake"

# Cancel previous run if a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: write-all

jobs:
  msvc:
    name: MSVC

    runs-on: windows-latest
    environment: Anomaly.Development

    env:
      configure-preset: ${{vars.CONFIGURE_PRESET_MSVC || 'MSVS.MSVC.Ninja.AVX'}}
      build-preset: ${{vars.BUILD_PRESET || 'Verified'}}
      target: ${{vars.TARGET || 'Anomaly.DX11'}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure build environment
      uses: ./.github/actions/setup-env
    
    - name: Build Binary
      uses: ./.github/actions/cmake
    
    - name: Upload Binary
      uses: ./.github/actions/upload-binary
    
    - name: Upload PDB
      uses: ./.github/actions/upload-pdb

  clang:
    name: Clang

    runs-on: windows-latest
    environment: Anomaly.Development

    env:
      configure-preset: ${{vars.CONFIGURE_PRESET_CLANG || 'System.Clang.AVX'}}
      build-preset: ${{vars.BUILD_PRESET || 'Verified'}}
      target: ${{vars.TARGET || 'Anomaly.DX11'}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure build environment
      uses: ./.github/actions/setup-env
    
    - name: Build Binary
      uses: ./.github/actions/cmake
    
    - name: Upload Binary
      uses: ./.github/actions/upload-binary
    
    - name: Upload PDB
      uses: ./.github/actions/upload-pdb

  gnu:
    name: GNU

    runs-on: windows-latest
    environment: Anomaly.Development

    if: false

    env:
      configure-preset: ${{vars.CONFIGURE_PRESET_GNU || 'System.GNU.AVX'}}
      build-preset: ${{vars.BUILD_PRESET || 'Verified'}}
      target: ${{vars.TARGET || 'Anomaly.DX11'}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure build environment
      uses: ./.github/actions/setup-env
    
    - name: Build Binary
      uses: ./.github/actions/cmake
    
    - name: Upload Binary
      uses: ./.github/actions/upload-binary
    
    - name: Upload PDB
      uses: ./.github/actions/upload-pdb

  gamedata:
    name: Gamedata
    runs-on: windows-latest
    environment: Anomaly.Gamedata

    env:
      configure-preset: 'MSVS.MSVC.Ninja.AVX'
      build-preset: 'Verified'
      target: 'Gamedata'
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure build environment
      uses: ./.github/actions/setup-env
    
    - name: Build Gamedata
      uses: ./.github/actions/build-gamedata
    
    - name: Upload Gamedata
      uses: ./.github/actions/upload-gamedata
