name: Anomaly CI

on:
  - push
  - pull_request

# Cancel previous run if a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: write-all

env:
  default-config-preset: MSVS.MSVC.Ninja.AVX
  build-preset: RelWithDebInfo
  gamedata-target: Gamedata
  packed-gamedata: 00_modded_exes_gamedata.db0
    
jobs:
  pack-gamedata:
    name: Gamedata
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snickerbockers/submodules-init@v4
      
      - name: Pack Gamedata
        uses: ./.github/actions/pack-gamedata
        with:
          build-preset: ${{env.build-preset}}
          config-preset: ${{env.default-config-preset}}
        
      - name: Upload Gamedata
        uses: ./.github/actions/upload-gamedata
        with:
          config-preset: ${{env.default-config-preset}}
          packed-gamedata: ${{env.packed-gamedata}}
  
  msvc:
    runs-on: windows-latest

    env:
      toolchain: MSVS.MSVC.Ninja

    strategy:
      matrix:
        avx:
          - true
          - false
      
    name: MSVS.MSVC.Ninja${{matrix.avx && '.AVX' || ''}}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialize Submodules
      uses: snickerbockers/submodules-init@v4
      
    - name: Setup MSBuild
      uses: './.github/actions/setup-msbuild'
    
    - name: Build Executables
      uses: './.github/actions/build-executables'
      with:
        toolchain: ${{env.toolchain}}
        avx: ${{matrix.avx}}
        build-preset: ${{env.build-preset}}
  
    - name: Upload DX8
      uses: './.github/actions/upload-executable'
      with:
        toolchain: ${{env.toolchain}}
        target: AnomalyDX8
        avx: ${{matrix.avx}}
        build-preset: ${{env.build-preset}}

    - name: Pack DX8 PDB
      uses: './.github/actions/pack-pdb'
      with:
        toolchain: ${{env.toolchain}}
        target: Anomaly.DX8
        avx: ${{matrix.avx}}
        build-preset: ${{env.build-preset}}

    - name: Upload DX8 PDB
      uses: './.github/actions/upload-pdb'
      with:
        toolchain: ${{env.toolchain}}
        target: Anomaly.DX8
        avx: ${{matrix.avx}}
        build-preset: ${{env.build-preset}}
  
    - name: Upload DX9
      uses: './.github/actions/upload-executable'
      with:
        toolchain: ${{env.toolchain}}
        target: AnomalyDX9
        avx: ${{matrix.avx}}
        build-preset: ${{env.build-preset}}

    - name: Pack DX9 PDB
      uses: './.github/actions/pack-pdb'
      with:
        toolchain: ${{env.toolchain}}
        target: Anomaly.DX9
        avx: ${{matrix.avx}}
        build-preset: ${{env.build-preset}}

    - name: Upload DX9 PDB
      uses: './.github/actions/upload-pdb'
      with:
        toolchain: ${{env.toolchain}}
        target: Anomaly.DX9
        avx: ${{matrix.avx}}
        build-preset: ${{env.build-preset}}
  
    - name: Upload DX10
      uses: './.github/actions/upload-executable'
      with:
        toolchain: ${{env.toolchain}}
        target: AnomalyDX10
        avx: ${{matrix.avx}}
        build-preset: ${{env.build-preset}}

    - name: Pack DX10 PDB
      uses: './.github/actions/pack-pdb'
      with:
        toolchain: ${{env.toolchain}}
        target: Anomaly.DX10
        avx: ${{matrix.avx}}
        build-preset: ${{env.build-preset}}

    - name: Upload DX10 PDB
      uses: './.github/actions/upload-pdb'
      with:
        toolchain: ${{env.toolchain}}
        target: Anomaly.DX10
        avx: ${{matrix.avx}}
        build-preset: ${{env.build-preset}}
  
    - name: Upload DX11
      uses: './.github/actions/upload-executable'
      with:
        toolchain: ${{env.toolchain}}
        target: AnomalyDX11
        avx: ${{matrix.avx}}
        build-preset: ${{env.build-preset}}

    - name: Pack DX11 PDB
      uses: './.github/actions/pack-pdb'
      with:
        toolchain: ${{env.toolchain}}
        target: Anomaly.DX11
        avx: ${{matrix.avx}}
        build-preset: ${{env.build-preset}}

    - name: Upload DX11 PDB
      uses: './.github/actions/upload-pdb'
      with:
        toolchain: ${{env.toolchain}}
        target: Anomaly.DX11
        avx: ${{matrix.avx}}
        build-preset: ${{env.build-preset}}
  
  clang:
    runs-on: windows-latest

    strategy:
      matrix:
        avx:
          - true
          - false
    
    name: System.Clang${{matrix.avx && '.AVX' || ''}}

    env:
      toolchain: System.Clang

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialize Submodules
      uses: snickerbockers/submodules-init@v4
      
    - name: Setup Clang
      uses: './.github/actions/setup-clang'
    
    - name: Build Executables
      uses: './.github/actions/build-executables'
      with:
        toolchain: ${{env.toolchain}}
        avx: ${{matrix.avx}}
        build-preset: ${{env.build-preset}}
  
  gnu:
    runs-on: windows-latest

    if: false

    strategy:
      matrix:
        avx:
          - true
          - false
    
    name: System.GNU${{matrix.avx && '.AVX' || ''}}

    env:
      toolchain: System.GNU

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialize Submodules
      uses: snickerbockers/submodules-init@v4
      
    - name: Build Executables
      uses: './.github/actions/build-executables'
      with:
        toolchain: ${{env.toolchain}}
        avx: ${{matrix.avx}}
        build-preset: ${{env.build-preset}}

  release:
    needs: [
      pack-gamedata,
      msvc
    ]
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Get Datetime
      id: datetime
      run: echo "::set-output name=today::$(date +'%-Y.%-m.%-d')"
        
    # Use the output from the `datetime` step
    - name: Get Version
      run: echo "VERSION ${{steps.datetime.outputs.today}}"
      env:
        VERSION: "${{steps.datetime.outputs.today}}"

    - name: Download artifacts
      uses: actions/download-artifact@v4.1.8
      with:
        artifact-ids:
          ${{env.packed-gamedata}}
          Anomaly.DX8
          Anomaly.DX8.PDB
          Anomaly.DX8.AVX
          Anomaly.DX8.AVX.PDB
          Anomaly.DX9
          Anomaly.DX9.PDB
          Anomaly.DX9.AVX
          Anomaly.DX9.AVX.PDB
          Anomaly.DX10
          Anomaly.DX10.PDB
          Anomaly.DX10.AVX
          Anomaly.DX10.AVX.PDB
          Anomaly.DX11
          Anomaly.DX11.PDB
          Anomaly.DX11.AVX
          Anomaly.DX11.AVX.PDB

    - name: Zip Exe folder
      run: |
        mkdir release
        mkdir release/bin
        mkdir release/db
        mkdir release/db/mods
        mv ${{env.packed-gamedata}}/*.db0 release/db/mods
        mv Anomaly.DX8/*.exe release/bin
        mv Anomaly.DX8.AVX/*.exe release/bin
        mv Anomaly.DX9/*.exe release/bin
        mv Anomaly.DX9.AVX/*.exe release/bin
        mv Anomaly.DX10/*.exe release/bin
        mv Anomaly.DX10.AVX/*.exe release/bin
        mv Anomaly.DX11/*.exe release/bin
        mv Anomaly.DX11.AVX/*.exe release/bin
        cd release
        zip -r 'STALKER-Anomaly-modded-exes_${{steps.datetime.outputs.today}}.zip' ./*
        mv 'STALKER-Anomaly-modded-exes_${{steps.datetime.outputs.today}}.zip' ../
        cd ..
      env: 
        RELEASE_NAME_FULL: "${{steps.datetime.outputs.today}}"

    - name: Move PDBs to folder
      run: |
        mkdir pdb
        mv Anomaly.DX8.PDB/*.zip pdb
        mv Anomaly.DX8.AVX.PDB/*.zip pdb
        mv Anomaly.DX9.PDB/*.zip pdb
        mv Anomaly.DX9.AVX.PDB/*.zip pdb
        mv Anomaly.DX10.PDB/*.zip pdb
        mv Anomaly.DX10.AVX.PDB/*.zip pdb
        mv Anomaly.DX11.PDB/*.zip pdb
        mv Anomaly.DX11.AVX.PDB/*.zip pdb

    - name: Publish
      uses: softprops/action-gh-release@v2.3.2
      with:
        files: |
          *.zip
          pdb/*.zip
        tag_name: "${{steps.datetime.outputs.today}}"
        generate_release_notes: true
        token: "${{ secrets.GITHUB_TOKEN }}"
    
    - name: Remove artifacts
      uses: c-hive/gha-remove-artifacts@v1.2.0
      with:
        age: "1 second"
